import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub — трейдинг и партнёрский доход со структурой и прозрачностью.',
    'home.tagline': 'Структура. Прозрачность. Контроль.',
    'home.mariaOnline': 'Мария — консультант в прямом эфире',
    'home.askMaria': 'Спросить Марию',
    'home.online': 'онлайн',
    'home.video': 'Видео',
    'home.chat': 'Чат',
    'home.trading': 'Трейдинг и стратегии',
    'home.partner': 'Партнёрская программа и доход',
    'home.promo': 'Акции',
    'home.schedule': 'Вебинары и расписание',
    'home.tutorials': 'Туториалы и гайды',
    'home.directLinks': 'Быстрые ссылки',
    'home.presentations': 'Презентации',
    'home.telegram': 'Telegram‑канал',
    'home.instagram': 'Instagram',
    'trading.title': 'Трейдинг и стратегии',
    'trading.subtitle': 'Ваш раздел трейдинга: брокер, копитрейдинг (Copy‑X) и Amplify 12x — в одном месте.',
    'trading.tagMarkets': 'Брокер TAG Markets',
    'trading.tagMarketsSubtitle': 'Регулируемое мультиактивное брокерское решение с MT5.',
    'trading.regulation': 'Регулирование:',
    'trading.regulationDesc': 'Лицензирован FSC Mauritius (лицензия GB21026474).',
    'trading.conditions': 'Условия:',
    'trading.conditionsDesc': 'Макс. плечо 1:500. Более 400 инструментов.',
    'trading.payouts': 'Выплаты:',
    'trading.payoutsDesc': 'Вывод средств в среднем в течение 24 часов.',
    'trading.scale': 'Масштаб:',
    'trading.scaleDesc': 'Более 500 000 трейдеров по миру; месячный объём торговли — свыше 200 млрд $.',
    'trading.security': 'Безопасность:',
    'trading.securityDesc': 'Защита данных и средств по банковским стандартам. Деньги остаются на вашем счёте.',
    'trading.copyX': 'Стратегии Copy‑X',
    'trading.copyXSubtitle': 'Автоматический копитрейдинг как вариант более «пассивного» участия.',
    'trading.copyXDesc': 'Автоматическое копирование профессиональных стратегий. Вы сохраняете 70% прибыли.',
    'trading.stats': 'Статистика:',
    'trading.statsDesc': 'Прозрачная статистика по каждой стратегии.',
    'trading.control': 'Контроль:',
    'trading.controlDesc': 'Можно отключить в любой момент. Деньги остаются на вашем счёте.',
    'trading.risk': 'Риск-менеджмент:',
    'trading.riskDesc': 'Консервативные стратегии: макс. 10% просадка, 0,3% риск на сделку.',
    'trading.vortex': 'Стратегия Vortex',
    'trading.vortexSubtitle': 'Скоро · эксклюзивно для сообщества JetUP',
    'trading.vortexComing': 'Скоро — эксклюзивно для сообщества JetUP!',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Масштабируйте собственный капитал до 12x.',
    'trading.amplifyDesc': 'Amplify — возможность увеличить торговый лимит у брокера при соблюдении правил риск‑менеджмента.',
    'trading.amplify12x': '12x:',
    'trading.amplify12xDesc': 'Имея свои 1 000 $, вы получаете 12 000 $ торгового капитала.',
    'trading.liquidity': 'Ликвидность:',
    'trading.liquidityDesc': 'Не модель проп‑фирмы — торговля на реальном рынке.',
    'trading.profit': 'Прибыль:',
    'trading.profitDesc': 'Вся прибыль принадлежит вам, вывод доступен в любой момент.',
    'trading.noCredit': 'Без кредита:',
    'trading.noCreditDesc': 'Без бонусов, без третьих сторон. Полный контроль.',
    'trading.start': 'Быстрый старт за 5 шагов',
    'trading.startSubtitle': 'От регистрации до первой сделки.',
    'trading.startStep1': '1. Регистрация:',
    'trading.startStep1Desc': 'Создайте аккаунт в JetUP IB Portal.',
    'trading.startStep2': '2. Соединение:',
    'trading.startStep2Desc': 'Зарегистрируйтесь у партнёрского брокера TAG Markets.',
    'trading.startStep3': '3. Установка:',
    'trading.startStep3Desc': 'Скачайте и установите MetaTrader 5.',
    'trading.startStep4': '4. Депозит:',
    'trading.startStep4Desc': 'Пополните торговый счёт у брокера (мин. 100 $).',
    'trading.startStep5': '5. Доступ:',
    'trading.startStep5Desc': 'Получите доступ к Copy‑X, сигналам и обучению.',
    'trading.faq': 'FAQ по трейдингу и TAG Markets',
    'trading.faqSubtitle': 'Часто задаваемые вопросы.',
    'trading.faqQ1': 'Мои деньги в безопасности?',
    'trading.faqA1': 'Да. Деньги находятся на вашем счёте в TAG Markets. Доступ есть только у вас. Вывод — в любой момент.',
    'trading.faqQ2': 'Сколько нужно инвестировать?',
    'trading.faqA2': 'Минимум 100 $ как клиент, 250 $ — если хотите стать партнёром.',
    'trading.faqQ3': 'Какой уровень риска?',
    'trading.faqA3': 'Консервативно: макс. 0,3% на сделку, макс. 10% просадка. Гарантий нет, но риск контролируемый.',
    'trading.faqQ4': 'Сколько я могу заработать?',
    'trading.faqA4': '2–5% в месяц по стратегиям Copy‑X. Результаты могут отличаться, гарантий нет.',
    'partner.title': 'Партнёрская программа и доход',
    'partner.subtitle': 'Доход на основе реального торгового оборота: комиссии, Profit Share, Infinity Bonus и Global Pools — плюс lifestyle‑вознаграждения.',
    'partner.toolkit': 'Ваш партнёрский набор инструментов',
    'partner.toolkitSubtitle': 'Инструменты, обучение и поддержка ИИ для вашего развития.',
    'partner.education': 'Обучение и знания:',
    'partner.educationDesc': 'Доступ к вебинарам, туториалам и обучению — от старта до продвинутого уровня.',
    'partner.community': 'Комьюнити и поддержка:',
    'partner.communityDesc': 'Активная Telegram‑группа, персональные контакты и командные созвоны.',
    'partner.aiTools': 'AI инструменты:',
    'partner.aiToolsDesc': 'Каждый партнёр может получить персональный Digital Hub со своей AI‑консультанткой (как Мария) — инструмент для команды и клиентов.',
    'partner.highlight': 'То, что вы видите сейчас — этот Digital Hub — может быть персонализирован для каждого партнёра JetUP и его команды.',
    'partner.commissions': 'Комиссии за лот',
    'partner.commissionsSubtitle': 'Доход за каждый проторгованный лот в команде.',
    'partner.amount': 'Вы получаете 10,50 $ за каждый проторгованный лот в вашей команде.',
    'partner.levels': 'До 10 уровней в глубину — чем активнее команда, тем выше доход.',
    'partner.basis': 'Все комиссии основаны на реальном торговом обороте, а не на пополнениях.',
    'partner.profitShare': 'Profit Share от команды',
    'partner.profitShareSubtitle': 'Доля от торговых результатов.',
    'partner.share': 'Вы получаете долю от реальных торговых результатов команды.',
    'partner.distribution': 'Распределение: 70% клиенту, 30% распределяется между трейдерами и структурой партнёрской программы.',
    'partner.profitBasis': 'Выплаты основаны на реальной прибыли, а не на обещаниях.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Дополнительные проценты при росте объёма команды.',
    'partner.infinityDesc': 'Дополнительный бонус‑процент при достижении определённых порогов объёма команды:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'от объёма 100 000 €',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'от объёма 300 000 €',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'от объёма 1 000 000 €',
    'partner.infinityStep4': 'До +5% при объёме команды 100k–20M $',
    'partner.rewards': 'Global Pools и lifestyle‑вознаграждения',
    'partner.rewardsSubtitle': 'Rolex, недвижимость, путешествия и другое.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Два пула по 1% прибыли компании каждый. Выплаты — каждые две недели.',
    'partner.lifestyleTitle': 'Lifestyle‑вознаграждения:',
    'partner.lifestyle1': 'Часы Rolex от объёма команды 500k $',
    'partner.lifestyle2': 'Сертификаты на недвижимость до 1 200 000 $',
    'partner.lifestyle3': 'Эксклюзивные поездки (Бали, Турция)',
    'partner.pdf': 'Partner PDF / презентация',
    'tutorials.title': 'Туториалы и гайды',
    'tutorials.subtitle': 'Короткие видео и пошаговые инструкции по трейдингу и партнёрской программе.',
    'tutorials.all': 'Все',
    'tutorials.forTraders': 'Для трейдеров',
    'tutorials.forPartners': 'Для партнёров',
    'promo.title': 'Акции и предложения',
    'promo.noPromos': 'Актуальных акций пока нет.',
    'common.back': 'Назад',
    'common.backToHub': 'Назад в Hub',
    'common.askMaria': 'Спросить Марию',
    'common.comingSoon': 'Скоро',
    'common.video': 'Видео',
    'common.guide': 'Гайд',
    'common.min': 'мин',
    'quick.whatIsJetup': 'Что такое JetUP?',
    'quick.howToStart': 'Как начать?',
    'quick.isSafe': 'Это безопасно?',
    'nav.home': 'Главная',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Общение',
    'nav.application': 'Заявка',
    'chat.maria': 'Мария',
    'chat.online': 'Онлайн',
    'chat.placeholder': 'Напишите сообщение...',
    'chat.greeting': 'Привет! Я Мария, ассистент JetUP. Расскажу про экосистему и помогу разобраться. Что тебя интересует?',
    'chat.typing': 'Мария печатает...',
    'video.startCall': 'Видеозвонок с Марией',
    'video.endCall': 'Завершить',
    'video.connecting': 'Подключение...',
    'app.title': 'Заявка на консультацию',
    'app.name': 'Ваше имя',
    'app.phone': 'Телефон',
    'app.email': 'Email',
    'app.submit': 'Отправить заявку',
    'app.success': 'Заявка отправлена!',
    'jetup.title': 'Экосистема JetUP',
    'jetup.desc': 'Современная платформа для выхода на финансовые рынки',
    'jetup.copyTrading': 'Copy-X Стратегии',
    'jetup.copyTradingDesc': 'Автоматическое копирование профессиональных стратегий с полным контролем',
    'jetup.signals': 'Торговые сигналы',
    'jetup.signalsDesc': 'Сигналы в реальном времени с точными уровнями входа и анализом',
    'jetup.academy': 'JetUP Академия',
    'jetup.academyDesc': 'Обучение трейдингу, управлению рисками и построению систем',
    'jetup.partner': 'Партнёрская программа',
    'jetup.partnerDesc': 'Структурированные модели дохода на основе реального объёма торгов',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Лицензированный брокер — ваш капитал всегда на вашем счёте',
    'jetup.howToStart': 'Как начать?',
    'jetup.startDesc': 'Регистрация → TAG Markets → MetaTrader 5 → Депозит → Доступ к инструментам',
    'jetup.minClient': 'Минимум для клиента: $100',
    'jetup.minPartner': 'Минимум для партнёра: $250',
    'scheduleTitle': 'Вебинары и расписание',
    'scheduleSubtitle': 'Еженедельные Zoom‑созвоны в прямом эфире с нашими экспертами. Бесплатно и без регистрации.',
    'scheduleAll': 'Все',
    'scheduleUhr': '',
    'scheduleExpect': 'Что вас ждёт:',
    'scheduleJoinZoom': 'Присоединиться к Zoom',
    'scheduleNoEvents': 'В этой категории нет событий.',
    'backToHub': 'Назад в Hub',
    'askMaria': 'Спросить Марию',
  },
  de: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub: Trading‑ und Partnereinkommen — strukturiert и transparent.',
    'home.tagline': 'Struktur. Transparenz. Kontrolle.',
    'home.mariaOnline': 'Maria – Live‑Beraterin',
    'home.askMaria': 'Maria fragen',
    'home.online': 'online',
    'home.video': 'Video',
    'home.chat': 'Chat',
    'home.trading': 'Trading & Strategien',
    'home.partner': 'Partnerprogramm & Einkommen',
    'home.promo': 'Aktionen',
    'home.schedule': 'Webinare & Termine',
    'home.tutorials': 'Tutorials & Guides',
    'home.directLinks': 'Direktlinks',
    'home.presentations': 'Präsentationen',
    'home.telegram': 'Telegram‑Kanal',
    'home.instagram': 'Instagram',
    'trading.title': 'Trading & Strategien',
    'trading.subtitle': 'Dein Trading‑Bereich: Broker, Copy‑Trading (Copy‑X) и Amplify 12x — an einem Ort.',
    'trading.tagMarkets': 'TAG Markets Broker',
    'trading.tagMarketsSubtitle': 'Regulierte Multi‑Asset‑Brokerage‑Lösung mit MT5.',
    'trading.regulation': 'Regulierung:',
    'trading.regulationDesc': 'Lizenziert durch die FSC Mauritius (Lizenz GB21026474).',
    'trading.conditions': 'Konditionen:',
    'trading.conditionsDesc': 'Max. Hebel 1:500. Über 400 Instrumente.',
    'trading.payouts': 'Auszahlungen:',
    'trading.payoutsDesc': 'Auszahlungen im Durchschnitt innerhalb von 24 Stunden.',
    'trading.scale': 'Skalierung:',
    'trading.scaleDesc': 'Über 500.000 Trader weltweit; monatliches Handelsvolumen über 200 Mrd. USD.',
    'trading.security': 'Sicherheit:',
    'trading.securityDesc': 'Daten‑ и Kapitalschutz nach Bankenstandards. Dein Geld bleibt auf deinem Konto.',
    'trading.copyX': 'Copy‑X Strategien',
    'trading.copyXSubtitle': 'Automatisches Copy‑Trading als potenzielle passive Einkommensquelle.',
    'trading.copyXDesc': 'Kopiere automatisch Profi‑Strategien. Du behältst 70% des Gewinns.',
    'trading.stats': 'Statistiken:',
    'trading.statsDesc': 'Transparente Performance‑Daten für jede Strategie.',
    'trading.control': 'Kontrolle:',
    'trading.controlDesc': 'Jederzeit deaktivierbar. Dein Geld bleibt auf deinem Konto.',
    'trading.risk': 'Risikomanagement:',
    'trading.riskDesc': 'Konservativer Ansatz: max. 10% Drawdown и 0,3% Risiko pro Trade.',
    'trading.vortex': 'Vortex Strategie',
    'trading.vortexSubtitle': 'Demnächst · exklusiv für die JetUP‑Community',
    'trading.vortexComing': 'Demnächst verfügbar — exklusiv für die JetUP‑Community.',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Skaliere dein Eigenkapital um bis zu 12x.',
    'trading.amplifyDesc': 'Amplify ist die Möglichkeit, dein Handelslimit beim Broker zu erhöhen — sofern du die Risikomanagement‑Regeln einhältst.',
    'trading.amplify12x': '12x Skalierung:',
    'trading.amplify12xDesc': 'Mit 1.000 USD Eigenkapital erhältst du 12.000 USD Handelskapital.',
    'trading.liquidity': 'Echte Liquidität:',
    'trading.liquidityDesc': 'Kein Prop‑Firm‑Modell — du handelst am echten Markt.',
    'trading.profit': '100% Profit:',
    'trading.profitDesc': 'Alle Gewinne gehören dir и können jederzeit ausgezahlt werden.',
    'trading.noCredit': 'Kein Kredit:',
    'trading.noCreditDesc': 'Kein Bonus, keine Drittparteien — volle Kontrolle.',
    'trading.start': 'Schnellstart в 5 Schritten',
    'trading.startSubtitle': 'Von der Registrierung bis zum ersten Trade.',
    'trading.startStep1': '1. Registrierung:',
    'trading.startStep1Desc': 'Erstelle ein Konto im JetUP IB Portal.',
    'trading.startStep2': '2. Verbindung:',
    'trading.startStep2Desc': 'Registriere dich beim Partner‑Broker TAG Markets.',
    'trading.startStep3': '3. Installation:',
    'trading.startStep3Desc': 'Lade den MetaTrader 5 herunter и installiere die App.',
    'trading.startStep4': '4. Einzahlung:',
    'trading.startStep4Desc': 'Lade dein Handelskonto beim Broker auf (min. 100 USD).',
    'trading.startStep5': '5. Zugang:',
    'trading.startStep5Desc': 'Erhalte Zugang zu Copy‑X, Signalen и Schulungen.',
    'trading.faq': 'FAQ zu Trading & TAG Markets',
    'trading.faqSubtitle': 'Häufige Fragen auf einen Blick.',
    'trading.faqQ1': 'Ist mein Geld sicher?',
    'trading.faqA1': 'Ja. Dein Geld liegt auf deinem eigenen Konto bei TAG Markets. Nur du hast Zugriff. Auszahlungen sind jederzeit möglich.',
    'trading.faqQ2': 'Wie viel muss ich investieren?',
    'trading.faqA2': 'Minimum 100 USD als Kunde, 250 USD, wenn du auch Partner werden möchtest.',
    'trading.faqQ3': 'Wie hoch ist das Risiko?',
    'trading.faqA3': 'Konservativer Ansatz: max. 0,3% pro Trade и max. 10% Drawdown. Keine Garantien — aber klar definierte Regeln.',
    'trading.faqQ4': 'Wie viel kann ich verdienen?',
    'trading.faqA4': 'Copy‑X Strategien zielen oft auf 2–5% pro Monat ab. Ergebnisse variieren; keine Garantien.',
    'partner.title': 'Partnerprogramm & Einkommen',
    'partner.subtitle': 'Verdiene an realem Handelsvolumen: Provisionen, Profit Share, Infinity Bonus и Global Pools — plus Lifestyle‑Belohnungen.',
    'partner.toolkit': 'Dein Partner‑Toolkit',
    'partner.toolkitSubtitle': 'Tools, Schulung и AI‑Power für deinen Erfolg.',
    'partner.education': 'Schulung & Wissen:',
    'partner.educationDesc': 'Zugang zu Webinaren, Tutorials и Trainings — vom Einstieg bis zum Experten‑Level.',
    'partner.community': 'Community & Support:',
    'partner.communityDesc': 'Aktive Telegram‑Gruppe, persönliche Ansprechpartner и Team‑Calls für den Austausch.',
    'partner.aiTools': 'AI‑Instrumente:',
    'partner.aiToolsDesc': 'Als Partner kannst du deinen eigenen personalisierten Digital Hub mit einer AI‑Beraterin (wie Maria) erhalten — ein smartes Tool für dich, dein Team и deine Kunden.',
    'partner.highlight': 'Genau das, was du hier siehst — dieser Digital Hub — kann für jeden JetUP‑Partner и sein Team personalisiert werden.',
    'partner.commissions': 'Lot‑Provisionen',
    'partner.commissionsSubtitle': 'Verdienst pro gehandeltem Lot in deinem Team.',
    'partner.amount': 'Du erhältst 10,50 USD pro gehandeltem Lot in deinem Team.',
    'partner.levels': 'Bis zu 10 Ebenen tief — je aktiver dein Team, desto mehr kannst du verdienen.',
    'partner.basis': 'Alle Provisionen basieren auf realem Handelsvolumen — nicht auf Einzahlungen.',
    'partner.profitShare': 'Profit Share vom Team',
    'partner.profitShareSubtitle': 'Beteiligung an realen Handelsergebnissen.',
    'partner.share': 'Du erhältst einen Anteil an den realen Handelsergebnissen deines Teams.',
    'partner.distribution': 'Gewinnverteilung: 70% Kunde, 30% werden zwischen Tradern и der Partnerstruktur verteilt.',
    'partner.profitBasis': 'Auszahlungen basieren auf echten Gewinnen — nicht auf Versprechen.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Extra‑Prozente bei wachsendem Teamvolumen.',
    'partner.infinityDesc': 'Zusätzlicher Bonus‑Prozentsatz, sobald bestimmte Schwellenwerte beim Teamvolumen erreicht werden:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'ab 100.000 EUR Volumen',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'ab 300.000 EUR Volumen',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'ab 1.000.000 EUR Volumen',
    'partner.infinityStep4': 'Bis zu +5% bei Teamvolumen von 100k bis 20M USD',
    'partner.rewards': 'Global Pools & Lifestyle‑Belohnungen',
    'partner.rewardsSubtitle': 'Rolex, Immobilien, Reisen и mehr.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Zwei Pools mit jeweils 1% des Unternehmensgewinns. Auszahlung alle zwei Wochen.',
    'partner.lifestyleTitle': 'Lifestyle‑Belohnungen:',
    'partner.lifestyle1': 'Rolex‑Uhren ab 500k USD Teamvolumen',
    'partner.lifestyle2': 'Immobilien‑Gutscheine bis zu 1.200.000 USD',
    'partner.lifestyle3': 'Exklusive Reisen (z. B. Bali, Türkei)',
    'partner.pdf': 'Partner PDF / Präsentation',
    'tutorials.title': 'Tutorials & Guides',
    'tutorials.subtitle': 'Kurze Videos и Schritt‑für‑Schritt‑Anleitungen zum Trading и Partnerprogramm.',
    'tutorials.all': 'Alle',
    'tutorials.forTraders': 'Für Trader',
    'tutorials.forPartners': 'Für Partner',
    'promo.title': 'Aktionen & Angebote',
    'promo.noPromos': 'Aktuell sind keine Aktionen verfügbar.',
    'common.back': 'Zurück',
    'common.backToHub': 'Zurück zum Hub',
    'common.askMaria': 'Maria fragen',
    'common.comingSoon': 'Demnächst',
    'common.video': 'Video',
    'common.guide': 'Guide',
    'common.min': 'Min.',
    'nav.home': 'Home',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Chat',
    'nav.application': 'Anfragen',
    'chat.maria': 'Maria',
    'chat.online': 'Online',
    'chat.placeholder': 'Nachricht schreiben...',
    'chat.greeting': 'Hallo! Ich bin Maria, die JetUP‑Assistentin. Ich erzähle dir alles über das Ökosystem и helfe dir, dich zurechtzufinden. Was interessiert dich?',
    'chat.typing': 'Maria schreibt...',
    'video.startCall': 'Videoanruf mit Maria',
    'video.endCall': 'Beenden',
    'video.connecting': 'Verbindung...',
    'app.title': 'Beratungsanfrage',
    'app.name': 'Dein Name',
    'app.phone': 'Telefon',
    'app.email': 'E‑Mail',
    'app.submit': 'Anfrage senden',
    'app.success': 'Anfrage gesendet!',
    'jetup.title': 'JetUP Ökosystem',
    'jetup.desc': 'Eine moderne Plattform für den Zugang zu den Finanzmärkten',
    'jetup.copyTrading': 'Copy‑X Strategien',
    'jetup.copyTradingDesc': 'Automatisches Kopieren von Profi‑Strategien mit voller Kontrolle',
    'jetup.signals': 'Trading‑Signale',
    'jetup.signalsDesc': 'Echtzeit‑Signale mit präzisen Einstiegspunkten и Analysen',
    'jetup.academy': 'JetUP Akademie',
    'jetup.academyDesc': 'Ausbildung в Trading, Risikomanagement и Systemdenken',
    'jetup.partner': 'Partnerprogramm',
    'jetup.partnerDesc': 'Strukturierte Einkommensmodelle basierend auf realem Handelsvolumen',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Lizenzierter Broker — dein Kapital bleibt immer auf deinem Konto',
    'jetup.howToStart': 'Wie starten?',
    'jetup.startDesc': 'Registrierung → TAG Markets → MetaTrader 5 → Einzahlung → Zugang zu Tools',
    'jetup.minClient': 'Minimum für Kunden: 100 USD',
    'jetup.minPartner': 'Minimum für Partner: 250 USD',
    'scheduleTitle': 'Webinare & Termine',
    'scheduleSubtitle': 'Wöchentliche Zoom‑Live‑Calls mit unseren Experten. Kostenlos и ohne Anmeldung.',
    'scheduleAll': 'Alle',
    'scheduleUhr': 'Uhr',
    'scheduleExpect': 'Was dich erwartet:',
    'scheduleJoinZoom': 'Zoom beitreten',
    'scheduleNoEvents': 'Keine Termine в dieser Kategorie.',
    'backToHub': 'Zurück zum Hub',
    'askMaria': 'Maria fragen',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved === 'ru' || saved === 'de') ? saved as Language : 'de';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['de'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
