import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub — трейдинг и партнёрский доход со структурой и прозрачностью.',
    'home.tagline': 'Структура. Прозрачность. Контроль.',
    'home.mariaOnline': 'Мария — консультант в прямом эфире',
    'home.askMaria': 'Спросить Марию',
    'home.online': 'онлайн',
    'home.video': 'Видео',
    'home.chat': 'Чат',
    'home.trading': 'Трейдинг и стратегии',
    'home.partner': 'Партнёрская программа и доход',
    'home.promo': 'Акции',
    'home.schedule': 'Вебинары и расписание',
    'home.tutorials': 'Туториалы и гайды',
    'home.directLinks': 'Быстрые ссылки',
    'home.presentations': 'Презентации',
    'home.telegram': 'Telegram‑канал',
    'home.instagram': 'Instagram',
    'trading.title': 'Трейдинг и стратегии',
    'trading.subtitle': 'Ваш раздел трейдинга: брокер, копитрейдинг (Copy‑X) и Amplify 12x — в одном месте.',
    'trading.tagMarkets': 'Брокер TAG Markets',
    'trading.tagMarketsSubtitle': 'Регулируемое мультиактивное брокерское решение с MT5.',
    'trading.regulation': 'Регулирование:',
    'trading.regulationDesc': 'Лицензирован FSC Mauritius (лицензия GB21026474).',
    'trading.conditions': 'Условия:',
    'trading.conditionsDesc': 'Макс. плечо 1:500. Более 400 инструментов.',
    'trading.payouts': 'Выплаты:',
    'trading.payoutsDesc': 'Вывод средств в среднем в течение 24 часов.',
    'trading.scale': 'Масштаб:',
    'trading.scaleDesc': 'Более 500 000 трейдеров по миру; месячный объём торговли — свыше 200 млрд $.',
    'trading.security': 'Безопасность:',
    'trading.securityDesc': 'Защита данных и средств по банковским стандартам. Деньги остаются на вашем счёте.',
    'trading.copyX': 'Стратегии Copy‑X',
    'trading.copyXSubtitle': 'Автоматический копитрейдинг как вариант более «пассивного» участия.',
    'trading.copyXDesc': 'Автоматическое копирование профессиональных стратегий. Вы сохраняете 70% прибыли.',
    'trading.stats': 'Статистика:',
    'trading.statsDesc': 'Прозрачная статистика по каждой стратегии.',
    'trading.control': 'Контроль:',
    'trading.controlDesc': 'Можно отключить в любой момент. Деньги остаются на вашем счёте.',
    'trading.risk': 'Риск-менеджмент:',
    'trading.riskDesc': 'Консервативные стратегии: макс. 10% просадка, 0,3% риск на сделку.',
    'trading.vortex': 'Стратегия Vortex',
    'trading.vortexSubtitle': 'Скоро · эксклюзивно для сообщества JetUP',
    'trading.vortexComing': 'Скоро — эксклюзивно для сообщества JetUP!',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Масштабируйте собственный капитал до 12x.',
    'trading.amplifyDesc': 'Amplify — возможность увеличить торговый лимит у брокера при соблюдении правил риск‑менеджмента.',
    'trading.amplify12x': '12x:',
    'trading.amplify12xDesc': 'Имея свои 1 000 $, вы получаете 12 000 $ торгового капитала.',
    'trading.liquidity': 'Ликвидность:',
    'trading.liquidityDesc': 'Не модель проп‑фирмы — торговля на реальном рынке.',
    'trading.profit': 'Прибыль:',
    'trading.profitDesc': 'Вся прибыль принадлежит вам, вывод доступен в любой момент.',
    'trading.noCredit': 'Без кредита:',
    'trading.noCreditDesc': 'Без бонусов, без третьих сторон. Полный контроль.',
    'trading.start': 'Быстрый старт за 5 шагов',
    'trading.startSubtitle': 'От регистрации до первой сделки.',
    'trading.startStep1': '1. Регистрация:',
    'trading.startStep1Desc': 'Создайте аккаунт в JetUP IB Portal.',
    'trading.startStep2': '2. Соединение:',
    'trading.startStep2Desc': 'Зарегистрируйтесь у партнёрского брокера TAG Markets.',
    'trading.startStep3': '3. Установка:',
    'trading.startStep3Desc': 'Скачайте и установите MetaTrader 5.',
    'trading.startStep4': '4. Депозит:',
    'trading.startStep4Desc': 'Пополните торговый счёт у брокера (мин. 100 $).',
    'trading.startStep5': '5. Доступ:',
    'trading.startStep5Desc': 'Получите доступ к Copy‑X, сигналам и обучению.',
    'trading.faq': 'FAQ по трейдингу и TAG Markets',
    'trading.faqSubtitle': 'Часто задаваемые вопросы.',
    'trading.faqQ1': 'Мои деньги в безопасности?',
    'trading.faqA1': 'Да. Деньги находятся на вашем счёте в TAG Markets. Доступ есть только у вас. Вывод — в любой момент.',
    'trading.faqQ2': 'Сколько нужно инвестировать?',
    'trading.faqA2': 'Минимум 100 $ как клиент, 250 $ — если хотите стать партнёром.',
    'trading.faqQ3': 'Какой уровень риска?',
    'trading.faqA3': 'Консервативно: макс. 0,3% на сделку, макс. 10% просадка. Гарантий нет, но риск контролируемый.',
    'trading.faqQ4': 'Сколько я могу заработать?',
    'trading.faqA4': '2–5% в месяц по стратегиям Copy‑X. Результаты могут отличаться, гарантий нет.',
    'partner.title': 'Партнёрская программа и доход',
    'partner.subtitle': 'Доход на основе реального торгового оборота: комиссии, Profit Share, Infinity Bonus и Global Pools — плюс lifestyle‑вознаграждения.',
    'partner.toolkit': 'Ваш партнёрский набор инструментов',
    'partner.toolkitSubtitle': 'Инструменты, обучение и поддержка ИИ для вашего развития.',
    'partner.education': 'Обучение и знания:',
    'partner.educationDesc': 'Доступ к вебинарам, туториалам и обучению — от старта до продвинутого уровня.',
    'partner.community': 'Комьюнити и поддержка:',
    'partner.communityDesc': 'Активная Telegram‑группа, персональные контакты и командные созвоны.',
    'partner.aiTools': 'AI инструменты:',
    'partner.aiToolsDesc': 'Каждый партнёр может получить персональный Digital Hub со своей AI‑консультанткой (как Мария) — инструмент для команды и клиентов.',
    'partner.highlight': 'То, что вы видите сейчас — этот Digital Hub — может быть персонализирован для каждого партнёра JetUP и его команды.',
    'partner.commissions': 'Комиссии за лот',
    'partner.commissionsSubtitle': 'Доход за каждый проторгованный лот в команде.',
    'partner.amount': 'Вы получаете 10,50 $ за каждый проторгованный лот в вашей команде.',
    'partner.levels': 'До 10 уровней в глубину — чем активнее команда, тем выше доход.',
    'partner.basis': 'Все комиссии основаны на реальном торговом обороте, а не на пополнениях.',
    'partner.profitShare': 'Profit Share от команды',
    'partner.profitShareSubtitle': 'Доля от торговых результатов.',
    'partner.share': 'Вы получаете долю от реальных торговых результатов команды.',
    'partner.distribution': 'Распределение: 70% клиенту, 30% распределяется между трейдерами и структурой партнёрской программы.',
    'partner.profitBasis': 'Выплаты основаны на реальной прибыли, а не на обещаниях.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Дополнительные проценты при росте объёма команды.',
    'partner.infinityDesc': 'Дополнительный бонус‑процент при достижении определённых порогов объёма команды:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'от объёма 100 000 €',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'от объёма 300 000 €',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'от объёма 1 000 000 €',
    'partner.infinityStep4': 'До +5% при объёме команды 100k–20M $',
    'partner.rewards': 'Global Pools и lifestyle‑вознаграждения',
    'partner.rewardsSubtitle': 'Rolex, недвижимость, путешествия и другое.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Два пула по 1% прибыли компании каждый. Выплаты — каждые две недели.',
    'partner.lifestyleTitle': 'Lifestyle‑вознаграждения:',
    'partner.lifestyle1': 'Часы Rolex от объёма команды 500k $',
    'partner.lifestyle2': 'Сертификаты на недвижимость до 1 200 000 $',
    'partner.lifestyle3': 'Эксклюзивные поездки (Бали, Турция)',
    'partner.pdf': 'Partner PDF / презентация',
    'tutorials.title': 'Туториалы и гайды',
    'tutorials.subtitle': 'Короткие видео и пошаговые инструкции по трейдингу и партнёрской программе.',
    'tutorials.all': 'Все',
    'tutorials.forTraders': 'Для трейдеров',
    'tutorials.forPartners': 'Для партнёров',
    'promo.title': 'Акции и предложения',
    'promo.noPromos': 'Актуальных акций пока нет.',
    'common.back': 'Назад',
    'common.backToHub': 'Назад в Hub',
    'common.askMaria': 'Спросить Марию',
    'common.comingSoon': 'Скоро',
    'common.video': 'Видео',
    'common.guide': 'Гайд',
    'common.min': 'мин',
    'quick.whatIsJetup': 'Что такое JetUP?',
    'quick.howToStart': 'Как начать?',
    'quick.isSafe': 'Это безопасно?',
    'nav.home': 'Главная',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Общение',
    'nav.application': 'Заявка',
    'chat.maria': 'Мария',
    'chat.online': 'Онлайн',
    'chat.placeholder': 'Напишите сообщение...',
    'chat.greeting': 'Привет! Я Мария, ассистент JetUP. Расскажу про экосистему и помогу разобраться. Что тебя интересует?',
    'chat.typing': 'Мария печатает...',
    'video.startCall': 'Видеозвонок с Марией',
    'video.endCall': 'Завершить',
    'video.connecting': 'Подключение...',
    'app.title': 'Заявка на консультацию',
    'app.name': 'Ваше имя',
    'app.phone': 'Телефон',
    'app.email': 'Email',
    'app.submit': 'Отправить заявку',
    'app.success': 'Заявка отправлена!',
    'jetup.title': 'Экосистема JetUP',
    'jetup.desc': 'Современная платформа для выхода на финансовые рынки',
    'jetup.copyTrading': 'Copy-X Стратегии',
    'jetup.copyTradingDesc': 'Автоматическое копирование профессиональных стратегий с полным контролем',
    'jetup.signals': 'Торговые сигналы',
    'jetup.signalsDesc': 'Сигналы в реальном времени с точными уровнями входа и анализом',
    'jetup.academy': 'JetUP Академия',
    'jetup.academyDesc': 'Обучение трейдингу, управлению рисками и построению систем',
    'jetup.partner': 'Партнёрская программа',
    'jetup.partnerDesc': 'Структурированные модели дохода на основе реального объёма торгов',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Лицензированный брокер — ваш капитал всегда на вашем счёте',
    'jetup.howToStart': 'Как начать?',
    'jetup.startDesc': 'Регистрация → TAG Markets → MetaTrader 5 → Депозит → Доступ к инструментам',
    'jetup.minClient': 'Минимум для клиента: $100',
    'jetup.minPartner': 'Минимум для партнёра: $250',
    'scheduleTitle': 'Вебинары и расписание',
    'scheduleSubtitle': 'Еженедельные Zoom‑созвоны в прямом эфире с нашими экспертами. Бесплатно и без регистрации.',
    'scheduleAll': 'Все',
    'scheduleUhr': '',
    'scheduleExpect': 'Что вас ждёт:',
    'scheduleJoinZoom': 'Присоединиться к Zoom',
    'scheduleNoEvents': 'В этой категории нет событий.',
    'backToHub': 'Назад в Hub',
    'askMaria': 'Спросить Марию',
  },
  en: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub: Trading and partner income — structured and transparent.',
    'home.tagline': 'Structure. Transparency. Control.',
    'home.mariaOnline': 'Maria – Live advisor',
    'home.askMaria': 'Ask Maria',
    'home.online': 'online',
    'home.video': 'Video',
    'home.chat': 'Chat',
    'home.trading': 'Trading & Strategies',
    'home.partner': 'Partner Program & Income',
    'home.promo': 'Promotions',
    'home.schedule': 'Webinars & Dates',
    'home.tutorials': 'Tutorials & Guides',
    'home.directLinks': 'Direct Links',
    'home.presentations': 'Presentations',
    'home.telegram': 'Telegram Channel',
    'home.instagram': 'Instagram',
    'trading.title': 'Trading & Strategies',
    'trading.subtitle': 'Your trading area: broker, copy trading (Copy‑X) and Amplify 12x — all in one place.',
    'trading.tagMarkets': 'TAG Markets Broker',
    'trading.tagMarketsSubtitle': 'Regulated multi‑asset brokerage with MT5.',
    'trading.regulation': 'Regulation:',
    'trading.regulationDesc': 'Licensed by FSC Mauritius (License GB21026474).',
    'trading.conditions': 'Conditions:',
    'trading.conditionsDesc': 'Max leverage 1:500. Over 400 instruments.',
    'trading.payouts': 'Payouts:',
    'trading.payoutsDesc': 'Withdrawals in average within 24 hours.',
    'trading.scale': 'Scale:',
    'trading.scaleDesc': 'Over 500,000 traders worldwide; monthly trading volume over 200bn USD.',
    'trading.security': 'Security:',
    'trading.securityDesc': 'Data and funds protection according to bank standards. Your money stays in your account.',
    'trading.copyX': 'Copy‑X Strategies',
    'trading.copyXSubtitle': 'Automatic copy trading for potential passive income.',
    'trading.copyXDesc': 'Automatically copy professional strategies. You keep 70% of the profit.',
    'trading.stats': 'Statistics:',
    'trading.statsDesc': 'Transparent performance data for each strategy.',
    'trading.control': 'Control:',
    'trading.controlDesc': 'Can be deactivated at any time. Your money stays in your account.',
    'trading.risk': 'Risk Management:',
    'trading.riskDesc': 'Conservative approach: max 10% drawdown and 0.3% risk per trade.',
    'trading.vortex': 'Vortex Strategy',
    'trading.vortexSubtitle': 'Coming soon · exclusive for the JetUP Community',
    'trading.vortexComing': 'Coming soon — exclusive for the JetUP Community.',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Scale your own capital up to 12x.',
    'trading.amplifyDesc': 'Amplify is the ability to increase your trading limit with the broker — provided you follow the risk management rules.',
    'trading.amplify12x': '12x Scaling:',
    'trading.amplify12xDesc': 'With 1,000 USD of your own capital, you get 12,000 USD of trading capital.',
    'trading.liquidity': 'Real Liquidity:',
    'trading.liquidityDesc': 'Not a prop firm model — you trade on the real market.',
    'trading.profit': '100% Profit:',
    'trading.profitDesc': 'All profit belongs to you and can be withdrawn at any time.',
    'trading.noCredit': 'No Credit:',
    'trading.noCreditDesc': 'No bonus, no third parties — full control.',
    'trading.start': 'Quick Start in 5 Steps',
    'trading.startSubtitle': 'From registration to the first trade.',
    'trading.startStep1': '1. Registration:',
    'trading.startStep1Desc': 'Create an account in the JetUP IB Portal.',
    'trading.startStep2': '2. Connection:',
    'trading.startStep2Desc': 'Register with the partner broker TAG Markets.',
    'trading.startStep3': '3. Installation:',
    'trading.startStep3Desc': 'Download MetaTrader 5 and install the app.',
    'trading.startStep4': '4. Deposit:',
    'trading.startStep4Desc': 'Top up your trading account with the broker (min. 100 USD).',
    'trading.startStep5': '5. Access:',
    'trading.startStep5Desc': 'Get access to Copy‑X, signals and training.',
    'trading.faq': 'FAQ on Trading & TAG Markets',
    'trading.faqSubtitle': 'Common questions at a glance.',
    'trading.faqQ1': 'Is my money safe?',
    'trading.faqA1': 'Yes. Your money is in your own account at TAG Markets. Only you have access. Withdrawals possible at any time.',
    'trading.faqQ2': 'How much do I need to invest?',
    'trading.faqA2': 'Minimum 100 USD as a client, 250 USD if you also want to become a partner.',
    'trading.faqQ3': 'What is the risk?',
    'trading.faqA3': 'Conservative approach: max 0.3% per trade and max 10% drawdown. No guarantees — but clearly defined rules.',
    'trading.faqQ4': 'How much can I earn?',
    'trading.faqA4': 'Copy‑X strategies often aim for 2–5% per month. Results vary; no guarantees.',
    'partner.title': 'Partner Program & Income',
    'partner.subtitle': 'Earn on real trading volume: commissions, Profit Share, Infinity Bonus and Global Pools — plus lifestyle rewards.',
    'partner.toolkit': 'Your Partner Toolkit',
    'partner.toolkitSubtitle': 'Tools, training and AI power for your success.',
    'partner.education': 'Training & Knowledge:',
    'partner.educationDesc': 'Access to webinars, tutorials and training — from entry to expert level.',
    'partner.community': 'Community & Support:',
    'partner.communityDesc': 'Active Telegram group, personal contacts and team calls for exchange.',
    'partner.aiTools': 'AI Instruments:',
    'partner.aiToolsDesc': 'As a partner, you can get your own personalized Digital Hub with an AI advisor (like Maria) — a smart tool for you, your team and your customers.',
    'partner.highlight': 'Exactly what you see here — this Digital Hub — can be personalized for every JetUP partner and their team.',
    'partner.commissions': 'Commissions per Lot',
    'partner.commissionsSubtitle': 'Earnings per traded lot in your team.',
    'partner.amount': 'You receive 10.50 USD per traded lot in your team.',
    'partner.levels': 'Up to 10 levels deep — the more active your team, the more you can earn.',
    'partner.basis': 'All commissions are based on real trading volume — not on deposits.',
    'partner.profitShare': 'Profit Share from the Team',
    'partner.profitShareSubtitle': 'Share of real trading results.',
    'partner.share': 'You receive a share of the real trading results of your team.',
    'partner.distribution': 'Profit distribution: 70% client, 30% distributed between traders and the partner structure.',
    'partner.profitBasis': 'Payouts are based on real profits — not on promises.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Extra percentage as your team volume grows.',
    'partner.infinityDesc': 'Additional bonus percentage once certain team volume thresholds are reached:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'from 100,000 EUR volume',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'from 300,000 EUR volume',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'from 1,000,000 EUR volume',
    'partner.infinityStep4': 'Up to +5% with team volume from 100k to 20M USD',
    'partner.rewards': 'Global Pools & Lifestyle Rewards',
    'partner.rewardsSubtitle': 'Rolex, real estate, travel and more.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Two pools with 1% of the company profit each. Payouts every two weeks.',
    'partner.lifestyleTitle': 'Lifestyle Rewards:',
    'partner.lifestyle1': 'Rolex watches from 500k USD team volume',
    'partner.lifestyle2': 'Real estate vouchers up to 1,200,000 USD',
    'partner.lifestyle3': 'Exclusive trips (e.g. Bali, Turkey)',
    'partner.pdf': 'Partner PDF / Presentation',
    'tutorials.title': 'Tutorials & Guides',
    'tutorials.subtitle': 'Short videos and step‑by‑step instructions for trading and the partner program.',
    'tutorials.all': 'All',
    'tutorials.forTraders': 'For Traders',
    'tutorials.forPartners': 'For Partners',
    'promo.title': 'Promotions & Offers',
    'promo.noPromos': 'No promotions available at the moment.',
    'common.back': 'Back',
    'common.backToHub': 'Back to Hub',
    'common.askMaria': 'Ask Maria',
    'common.comingSoon': 'Coming soon',
    'common.video': 'Video',
    'common.guide': 'Guide',
    'common.min': 'min',
    'nav.home': 'Home',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Chat',
    'nav.application': 'Apply',
    'chat.maria': 'Maria',
    'chat.online': 'Online',
    'chat.placeholder': 'Type a message...',
    'chat.greeting': "Hi! I'm Maria, JetUP assistant. I'll tell you about the ecosystem and help you figure things out. What interests you?",
    'chat.typing': 'Maria is typing...',
    'video.startCall': 'Video call with Maria',
    'video.endCall': 'End call',
    'video.connecting': 'Connecting...',
    'app.title': 'Consultation Request',
    'app.name': 'Your name',
    'app.phone': 'Phone',
    'app.email': 'Email',
    'app.submit': 'Submit request',
    'app.success': 'Request sent!',
    'jetup.title': 'JetUP Ecosystem',
    'jetup.desc': 'A modern platform for entering the financial markets',
    'jetup.copyTrading': 'Copy-X Strategies',
    'jetup.copyTradingDesc': 'Automatically copy professional strategies with full control',
    'jetup.signals': 'Trading Signals',
    'jetup.signalsDesc': 'Real-time signals with precise entry levels and analysis',
    'jetup.academy': 'JetUP Academy',
    'jetup.academyDesc': 'Trading education, risk management and systems thinking',
    'jetup.partner': 'Partner Program',
    'jetup.partnerDesc': 'Structured income models based on real trading volume',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Licensed broker — your capital always stays in your account',
    'jetup.howToStart': 'How to start?',
    'jetup.startDesc': 'Register → TAG Markets → MetaTrader 5 → Deposit → Access tools',
    'jetup.minClient': 'Minimum for client: $100',
    'jetup.minPartner': 'Minimum for partner: $250',
    'scheduleTitle': 'Webinars & Schedule',
    'scheduleSubtitle': 'Weekly live Zoom calls with our experts. Free and no registration needed.',
    'scheduleAll': 'All',
    'scheduleUhr': '',
    'scheduleExpect': 'What to expect:',
    'scheduleJoinZoom': 'Join Zoom Call',
    'scheduleNoEvents': 'No events in this category.',
    'backToHub': 'Back to Hub',
    'askMaria': 'Ask Maria',
  },
  de: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub: Trading und Partner‑Einkommen — strukturiert und transparent.',
    'home.tagline': 'Struktur. Transparenz. Kontrolle.',
    'home.mariaOnline': 'Maria – Live‑Beraterin',
    'home.askMaria': 'Maria fragen',
    'home.online': 'online',
    'home.video': 'Video',
    'home.chat': 'Chat',
    'home.trading': 'Trading & Strategien',
    'home.partner': 'Partnerprogramm & Einkommen',
    'home.promo': 'Aktionen',
    'home.schedule': 'Webinare & Termine',
    'home.tutorials': 'Tutorials & Guides',
    'home.directLinks': 'Direkte Links',
    'home.presentations': 'Präsentationen',
    'home.telegram': 'Telegram‑Kanal',
    'home.instagram': 'Instagram',
    'trading.title': 'Trading & Strategien',
    'trading.subtitle': 'Dein Trading‑Bereich: Broker, Copy‑Trading (Copy‑X) und Amplify 12x — alles an einem Ort.',
    'trading.tagMarkets': 'Broker: TAG Markets',
    'trading.tagMarketsSubtitle': 'Regulierte Multi‑Asset‑Plattform mit MT5.',
    'trading.regulation': 'Regulierung:',
    'trading.regulationDesc': 'Lizenziert durch die FSC Mauritius (Lizenz GB21026474).',
    'trading.conditions': 'Bedingungen:',
    'trading.conditionsDesc': 'Hebel bis 1:500. Über 400 Instrumente.',
    'trading.payouts': 'Auszahlung:',
    'trading.payoutsDesc': 'Im Durchschnitt innerhalb von 24 Stunden.',
    'trading.scale': 'Umfang:',
    'trading.scaleDesc': 'Über 500.000 Trader weltweit, monatliches Handelsvolumen über 200 Mrd. USD.',
    'trading.security': 'Sicherheit:',
    'trading.securityDesc': 'Schutz von Daten und Kundengeldern nach Bankstandards. Dein Geld bleibt auf deinem eigenen Konto.',
    'trading.copyX': 'Copy-X Strategien',
    'trading.copyXSubtitle': 'Automatisches Copy‑Trading für potenziell passives Einkommen.',
    'trading.copyXDesc': 'Professionelle Strategien automatisch kopieren. Du behältst 70% des Gewниnns.',
    'trading.stats': 'Volle Statistik:',
    'trading.statsDesc': 'Transparente Performance‑Daten für jede Strategie.',
    'trading.control': 'Kontrolle:',
    'trading.controlDesc': 'Jederzeit pausierbar. Dein Geld bleibt auf deinem Konto.',
    'trading.risk': 'Risikomanagement:',
    'trading.riskDesc': 'Konservativer Ansatz: max. 10% Drawdown und 0,3% Risiko pro Trade.',
    'trading.vortex': 'Vortex Strategy',
    'trading.vortexSubtitle': 'Coming soon · exklusiv für die JetUP Community',
    'trading.vortexComing': 'Coming soon — exklusiv für die JetUP Community.',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Skaliere dein Eigenkapital um bis zu das 12‑Fache.',
    'trading.amplifyDesc': 'Amplify erhöht dein Handelslimit beim Broker — sofern du die Risikomanagement‑Regeln einhältst.',
    'trading.amplify12x': '12x Skalierung:',
    'trading.amplify12xDesc': 'Mit 1.000 USD eigenem Kapital erhältst du 12.000 USD Handelskapital.',
    'trading.liquidity': 'Echte Liquidität:',
    'trading.liquidityDesc': 'Kein Prop-Firm-Modell — du handelst am realen Markt.',
    'trading.profit': '100% Gewinn:',
    'trading.profitDesc': 'Deйн gesamter Gewinn gehört dir und ist jederzeit auszahlbar.',
    'trading.noCredit': 'Kein Kredit:',
    'trading.noCreditDesc': 'Keн Bonus, keine Drittparteien — volle Kontrolle.',
    'trading.start': 'Schnellstart in 5 Schritten',
    'trading.startSubtitle': 'Von der Registrierung bis zum ersten Trade.',
    'trading.startStep1': '1. Registrierung:',
    'trading.startStep1Desc': 'Erstelle ein Konto im JetUP IB‑Portal.',
    'trading.startStep2': '2. Verbindung:',
    'trading.startStep2Desc': 'Registriere dich beim Partner-Broker TAG Markets.',
    'trading.startStep3': '3. Installation:',
    'trading.startStep3Desc': 'Lade MetaTrader 5 herunter und installiere die App.',
    'trading.startStep4': '4. Einzahlung:',
    'trading.startStep4Desc': 'Lade dein Handelskonto beim Broker auf (mind. 100 USD).',
    'trading.startStep5': '5. Zugang:',
    'trading.startStep5Desc': 'Erhalte Zugang zu Copy-X, Signalen und Schulungen.',
    'trading.faq': 'FAQ zu Trading & TAG Markets',
    'trading.faqSubtitle': 'Häufige Fragen auf einen Blick.',
    'trading.faqQ1': 'Ist mein Geld sicher?',
    'trading.faqA1': 'Ja. Dein Geld liegt auf deinem eigenen Konto bei TAG Markets. Nur du hast Zugriff. Jederzeit auszahlbar.',
    'trading.faqQ2': 'Wie viel muss ich investieren?',
    'trading.faqA2': 'Mindestens 100 USD als Kunde, 250 USD, wenn du zusätzlich Partner werden möchtest.',
    'trading.faqQ3': 'Wie hoch ist das Risiko?',
    'trading.faqA3': 'Konservativer Ansatz: max. 0,3% pro Trade und max. 10% Drawdown. Keine Garantien — aber klar definierte Regeln.',
    'trading.faqQ4': 'Wie viel kann ich verdienen?',
    'trading.faqA4': 'Bei Copy‑X‑Strategien werden oft 2–5% pro Monat angestrebt. Ergebnisse variieren; keine Garantien.',
    'partner.title': 'Partnerprogramm & Einkommen',
    'partner.subtitle': 'Verdiene am realen Handelsvolumen: Provisionen, Profit‑Share, Infinity Bonus und Global Pools — plus Lifestyle‑Rewards.',
    'partner.toolkit': 'Dein Partner-Toolkit',
    'partner.toolkitSubtitle': 'Tools, Training und KI‑Power für deinen Erfolg.',
    'partner.education': 'Schulung & Wissen:',
    'partner.educationDesc': 'Zugang zu Webinaren, Tutorials und Trainings — vom Einstieg bis zum Expertenlevel.',
    'partner.community': 'Community & Support:',
    'partner.communityDesc': 'Aktive Telegram‑Gruppe, persönliche Ansprechpartner und Team‑Calls zum Austausch.',
    'partner.aiTools': 'AI-Instrumentе:',
    'partner.aiToolsDesc': 'Als Partner kannst du deinen eigenen personalisierten Digital Hub with KI‑Beraterin (wie Maria) erhalten — ein smartes Tool für dich, dein Team und deine Kunden.',
    'partner.highlight': 'Genau das, was du hier siehst — diesen Digital Hub — kann jeder JetUP‑Partner für sich und sein Team personalisieren lassen.',
    'partner.commissions': 'Provisionen pro Lot',
    'partner.commissionsSubtitle': 'Verdienst pro gehandeltem Lot in deinem Team.',
    'partner.amount': 'Du erhältst 10,50 USD pro gehandeltem Lot in deinem Team.',
    'partner.levels': 'Bis zu 10 Ebenen tief — je aktiver dein Team, desto mehr kannst du verdienen.',
    'partner.basis': 'Alle Provisionen basieren auf realem Handelsvolumen — nicht auf Einzahlungen.',
    'partner.profitShare': 'Profit‑Share aus dem Team',
    'partner.profitShareSubtitle': 'Anteil an realen Handelsergebnissen.',
    'partner.share': 'Du erhältst einen Anteil an den realen Handelsergebnissen deines Teams.',
    'partner.distribution': 'Gewinnverteilung: 70% Kunde, 30% werden auf Trader und die Partnerstruktur verteilt.',
    'partner.profitBasis': 'Auszahlungen basieren auf echten Gewinnen — nicht auf Versprechen.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Extra‑Prozente bei wachsendem Teamvolumen.',
    'partner.infinityDesc': 'Zusätzlicher Bonus‑Prozentsatz, sobald bestimmte Teamvolumen‑Schwellen erreicht werden:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'ab 100.000 EUR Volumen',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'ab 300.000 EUR Volumen',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'ab 1.000.000 EUR Volumen',
    'partner.infinityStep4': 'Bis zu +5% bei einem Teamvolumen von 100k bis 20M USD',
    'partner.rewards': 'Global Pools & Lifestyle-Rewards',
    'partner.rewardsSubtitle': 'Rolex, Immobilien, Reisen und mehr.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Zwei Pools mit jeweils 1% des Unternehmensgewinns. Auszahlungen alle zwei Wochen.',
    'partner.lifestyleTitle': 'Lifestyle-Belohnungen:',
    'partner.lifestyle1': 'Rolex‑Uhren ab 500k USD Teamvolumen',
    'partner.lifestyle2': 'Immobilien‑Gutscheine bis 1.200.000 USD',
    'partner.lifestyle3': 'Exklusive Reisen (z. B. Bali, Türkei)',
    'partner.pdf': 'Partner‑PDF / Präsentation',
    'tutorials.title': 'Tutorials & Guides',
    'tutorials.subtitle': 'Kurzvideos und Schritt‑für‑Schritt‑Anleitungen für Trading und Partnerprogramm.',
    'tutorials.all': 'Alle',
    'tutorials.forTraders': 'Für Trader',
    'tutorials.forPartners': 'Für Partner',
    'promo.title': 'Aktionen & Angebote',
    'promo.noPromos': 'Aktuell sind keine Aktionen verfügbar.',
    'common.back': 'Zurück',
    'common.backToHub': 'Zurück zum Hub',
    'common.askMaria': 'Frag Maria',
    'common.comingSoon': 'Coming soon',
    'common.video': 'Video',
    'common.guide': 'Guide',
    'common.min': 'min',
    'nav.home': 'Startseite',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Chat',
    'nav.application': 'Anfrage',
    'chat.maria': 'Maria',
    'chat.online': 'Online',
    'chat.placeholder': 'Nachricht schreiben …',
    'chat.greeting': 'Hallo! Ich bin Maria, deine JetUP‑Assistentin. Ich erkläre dir das Ökosystem und helfe dir weiter. Was möchtest du wissen?',
    'chat.typing': 'Maria tippt...',
    'video.startCall': 'Videoanruf mit Maria',
    'video.endCall': 'Beenden',
    'video.connecting': 'Verbindung wird hergestellt...',
    'app.title': 'Beratungsanfrage',
    'app.name': 'Ihr Name',
    'app.phone': 'Telefon',
    'app.email': 'E-Mail',
    'app.submit': 'Anfrage senden',
    'app.success': 'Anfrage gesendet!',
    'jetup.title': 'JetUP Ökosystem',
    'jetup.desc': 'Eine moderne Plattform für den Einstieg in die Finanzmärkte',
    'jetup.copyTrading': 'Copy-X Strategien',
    'jetup.copyTradingDesc': 'Automatisches Kopieren professioneller Strategien mit voller Kontrolle',
    'jetup.signals': 'Handelssignale',
    'jetup.signalsDesc': 'Echtzeit-Signale mit präzisen Einstiegsniveaus und Analyse',
    'jetup.academy': 'JetUP Академия',
    'jetup.academyDesc': 'Trading-Ausbildung, Risikomanagement und Systemdenken',
    'jetup.partner': 'Partnerprogramm',
    'jetup.partnerDesc': 'Strukturierte Einkommensmodelle basierend auf realem Handelsvolumen',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Lizenzierter Broker — Ihr Kapital bleibt immer auf Ihrem Konto',
    'jetup.howToStart': 'Wie starte ich?',
    'jetup.startDesc': 'Registrierung → TAG Markets → MetaTrader 5 → Einzahlung → Zugang zu Tools',
    'jetup.minClient': 'Minimum für Kunden: 100 $',
    'jetup.minPartner': 'Minimum für Partner: 250 $',
    'scheduleTitle': 'Webinare & Termine',
    'scheduleSubtitle': 'Wöchentliche Live‑Zoom‑Calls mit unseren Experten. Kostenlos und ohne Anmeldung.',
    'scheduleAll': 'Alle',
    'scheduleUhr': 'Uhr',
    'scheduleExpect': 'Das erwartet dich:',
    'scheduleJoinZoom': 'Zum Zoom Call',
    'scheduleNoEvents': 'Keine Termine in dieser Kategorie.',
    'backToHub': 'Zurück zum Hub',
    'askMaria': 'Frag Maria',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    if (!saved) return 'de';
    return saved as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
