import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'ru' | 'de' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  ru: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub — трейдинг и партнёрский доход со структурой и прозрачностью.',
    'home.tagline': 'Структура. Прозрачность. Контроль.',
    'home.mariaOnline': 'Мария — консультант в прямом эфире',
    'home.askMaria': 'Спросить Марию',
    'home.online': 'онлайн',
    'home.video': 'Видео',
    'home.chat': 'Чат',
    'home.trading': 'Трейдинг и стратегии',
    'home.partner': 'Партнёрская программа и доход',
    'home.promo': 'Акции',
    'home.schedule': 'Вебинары и расписание',
    'home.tutorials': 'Туториалы и гайды',
    'home.directLinks': 'Быстрые ссылки',
    'home.presentations': 'Презентации',
    'home.telegram': 'Telegram‑канал',
    'home.instagram': 'Instagram',
    'trading.title': 'Трейдинг и стратегии',
    'trading.subtitle': 'Ваш раздел трейдинга: брокер, копитрейдинг (Copy‑X) и Amplify 12x — в одном месте.',
    'trading.tagMarkets': 'Брокер TAG Markets',
    'trading.tagMarketsSubtitle': 'Регулируемое мультиактивное брокерское решение с MT5.',
    'trading.regulation': 'Регулирование:',
    'trading.regulationDesc': 'Лицензирован FSC Mauritius (лицензия GB21026474).',
    'trading.conditions': 'Условия:',
    'trading.conditionsDesc': 'Макс. плечо 1:500. Более 400 инструментов.',
    'trading.payouts': 'Выплаты:',
    'trading.payoutsDesc': 'Вывод средств в среднем в течение 24 часов.',
    'trading.scale': 'Масштаб:',
    'trading.scaleDesc': 'Более 500 000 трейдеров по миру; месячный объём торговли — свыше 200 млрд $.',
    'trading.security': 'Безопасность:',
    'trading.securityDesc': 'Защита данных и средств по банковским стандартам. Деньги остаются на вашем счёте.',
    'trading.copyX': 'Стратегии Copy‑X',
    'trading.copyXSubtitle': 'Автоматический копитрейдинг как вариант более «пассивного» участия.',
    'trading.copyXDesc': 'Автоматическое копирование профессиональных стратегий. Вы сохраняете 70% прибыли.',
    'trading.stats': 'Статистика:',
    'trading.statsDesc': 'Прозрачная статистика по каждой стратегии.',
    'trading.control': 'Контроль:',
    'trading.controlDesc': 'Можно отключить в любой момент. Деньги остаются на вашем счёте.',
    'trading.risk': 'Риск-менеджмент:',
    'trading.riskDesc': 'Консервативные стратегии: макс. 10% просадка, 0,3% риск на сделку.',
    'trading.vortex': 'Стратегия Vortex',
    'trading.vortexSubtitle': 'Скоро · эксклюзивно для сообщества JetUP',
    'trading.vortexComing': 'Скоро — эксклюзивно для сообщества JetUP!',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Масштабируйте собственный капитал до 12x.',
    'trading.amplifyDesc': 'Amplify — возможность увеличить торговый лимит у брокера при соблюдении правил риск‑менеджмента.',
    'trading.amplify12x': '12x:',
    'trading.amplify12xDesc': 'Имея свои 1 000 $, вы получаете 12 000 $ торгового капитала.',
    'trading.liquidity': 'Ликвидность:',
    'trading.liquidityDesc': 'Не модель проп‑фирмы — торговля на реальном рынке.',
    'trading.profit': 'Прибыль:',
    'trading.profitDesc': 'Вся прибыль принадлежит вам, вывод доступен в любой момент.',
    'trading.noCredit': 'Без кредита:',
    'trading.noCreditDesc': 'Без бонусов, без третьих сторон. Полный контроль.',
    'trading.start': 'Быстрый старт за 5 шагов',
    'trading.startSubtitle': 'От регистрации до первой сделки.',
    'trading.startStep1': '1. Регистрация:',
    'trading.startStep1Desc': 'Создайте аккаунт в JetUP IB Portal.',
    'trading.startStep2': '2. Соединение:',
    'trading.startStep2Desc': 'Зарегистрируйтесь у партнёрского брокера TAG Markets.',
    'trading.startStep3': '3. Установка:',
    'trading.startStep3Desc': 'Скачайте и установите MetaTrader 5.',
    'trading.startStep4': '4. Депозит:',
    'trading.startStep4Desc': 'Пополните торговый счёт у брокера (мин. 100 $).',
    'trading.startStep5': '5. Доступ:',
    'trading.startStep5Desc': 'Получите доступ к Copy‑X, сигналам и обучению.',
    'trading.faq': 'FAQ по трейдингу и TAG Markets',
    'trading.faqSubtitle': 'Часто задаваемые вопросы.',
    'trading.faqQ1': 'Мои деньги в безопасности?',
    'trading.faqA1': 'Да. Деньги находятся на вашем счёте в TAG Markets. Доступ есть только у вас. Вывод — в любой момент.',
    'trading.faqQ2': 'Сколько нужно инвестировать?',
    'trading.faqA2': 'Минимум 100 $ как клиент, 250 $ — если хотите стать партнёром.',
    'trading.faqQ3': 'Какой уровень риска?',
    'trading.faqA3': 'Консервативно: макс. 0,3% на сделку, макс. 10% просадка. Гарантий нет, но риск контролируемый.',
    'trading.faqQ4': 'Сколько я могу заработать?',
    'trading.faqA4': '2–5% в месяц по стратегиям Copy‑X. Результаты могут отличаться, гарантий нет.',
    'partner.title': 'Партнёрская программа и доход',
    'partner.subtitle': 'Доход на основе реального торгового оборота: комиссии, Profit Share, Infinity Bonus и Global Pools — плюс lifestyle‑вознаграждения.',
    'partner.toolkit': 'Ваш партнёрский набор инструментов',
    'partner.toolkitSubtitle': 'Инструменты, обучение и поддержка ИИ для вашего развития.',
    'partner.education': 'Обучение и знания:',
    'partner.educationDesc': 'Доступ к вебинарам, туториалам и обучению — от старта до продвинутого уровня.',
    'partner.community': 'Комьюнити и поддержка:',
    'partner.communityDesc': 'Активная Telegram‑группа, персональные контакты и командные созвоны.',
    'partner.aiTools': 'AI инструменты:',
    'partner.aiToolsDesc': 'Каждый партнёр может получить персональный Digital Hub со своей AI‑консультанткой (как Мария) — инструмент для команды и клиентов.',
    'partner.highlight': 'То, что вы видите сейчас — этот Digital Hub — может быть персонализирован для каждого партнёра JetUP и его команды.',
    'partner.commissions': 'Комиссии за лот',
    'partner.commissionsSubtitle': 'Доход за каждый проторгованный лот в команде.',
    'partner.amount': 'Вы получаете 10,50 $ за каждый проторгованный лот в вашей команде.',
    'partner.levels': 'До 10 уровней в глубину — чем активнее команда, тем выше доход.',
    'partner.basis': 'Все комиссии основаны на реальном торговом обороте, а не на пополнениях.',
    'partner.profitShare': 'Profit Share от команды',
    'partner.profitShareSubtitle': 'Доля от торговых результатов.',
    'partner.share': 'Вы получаете долю от реальных торговых результатов команды.',
    'partner.distribution': 'Распределение: 70% клиенту, 30% распределяется между трейдерами и структурой партнёрской программы.',
    'partner.profitBasis': 'Выплаты основаны на реальной прибыли, а не на обещаниях.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Дополнительные проценты при росте объёма команды.',
    'partner.infinityDesc': 'Дополнительный бонус‑процент при достижении определённых порогов объёма команды:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'от объёма 100 000 €',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'от объёма 300 000 €',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'от объёма 1 000 000 €',
    'partner.infinityStep4': 'До +5% при объёме команды 100k–20M $',
    'partner.rewards': 'Global Pools и lifestyle‑вознаграждения',
    'partner.rewardsSubtitle': 'Rolex, недвижимость, путешествия и другое.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Два пула по 1% прибыли компании каждый. Выплаты — каждые две недели.',
    'partner.lifestyleTitle': 'Lifestyle‑вознаграждения:',
    'partner.lifestyle1': 'Часы Rolex от объёма команды 500k $',
    'partner.lifestyle2': 'Сертификаты на недвижимость до 1 200 000 $',
    'partner.lifestyle3': 'Эксклюзивные поездки (Бали, Турция)',
    'partner.pdf': 'Partner PDF / презентация',
    'tutorials.title': 'Туториалы и гайды',
    'tutorials.subtitle': 'Короткие видео и пошаговые инструкции по трейдингу и партнёрской программе.',
    'tutorials.all': 'Все',
    'tutorials.forTraders': 'Для трейдеров',
    'tutorials.forPartners': 'Для партнёров',
    'promo.title': 'Акции и предложения',
    'promo.noPromos': 'Актуальных акций пока нет.',
    'common.back': 'Назад',
    'common.backToHub': 'Назад в Hub',
    'common.askMaria': 'Спросить Марию',
    'common.comingSoon': 'Скоро',
    'common.video': 'Видео',
    'common.guide': 'Гайд',
    'common.min': 'мин',
    'quick.whatIsJetup': 'Что такое JetUP?',
    'quick.howToStart': 'Как начать?',
    'quick.isSafe': 'Это безопасно?',
    'nav.home': 'Главная',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Общение',
    'nav.application': 'Заявка',
    'chat.maria': 'Мария',
    'chat.online': 'Онлайн',
    'chat.placeholder': 'Напишите сообщение...',
    'chat.greeting': 'Привет! Я Мария, ассистент JetUP. Расскажу про экосистему и помогу разобраться. Что тебя интересует?',
    'chat.typing': 'Мария печатает...',
    'video.startCall': 'Видеозвонок с Марией',
    'video.endCall': 'Завершить',
    'video.connecting': 'Подключение...',
    'app.title': 'Заявка на консультацию',
    'app.name': 'Ваше имя',
    'app.phone': 'Телефон',
    'app.email': 'Email',
    'app.submit': 'Отправить заявку',
    'app.success': 'Заявка отправлена!',
    'jetup.title': 'Экосистема JetUP',
    'jetup.desc': 'Современная платформа для выхода на финансовые рынки',
    'jetup.copyTrading': 'Copy-X Стратегии',
    'jetup.copyTradingDesc': 'Автоматическое копирование профессиональных стратегий с полным контролем',
    'jetup.signals': 'Торговые сигналы',
    'jetup.signalsDesc': 'Сигналы в реальном времени с точными уровнями входа и анализом',
    'jetup.academy': 'JetUP Академия',
    'jetup.academyDesc': 'Обучение трейдингу, управлению рисками и построению систем',
    'jetup.partner': 'Партнёрская программа',
    'jetup.partnerDesc': 'Структурированные модели дохода на основе реального объёма торгов',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Лицензированный брокер — ваш капитал всегда на вашем счёте',
    'jetup.howToStart': 'Как начать?',
    'jetup.startDesc': 'Регистрация → TAG Markets → MetaTrader 5 → Депозит → Доступ к инструментам',
    'jetup.minClient': 'Минимум для клиента: $100',
    'jetup.minPartner': 'Минимум для партнёра: $250',
    'scheduleTitle': 'Вебинары и расписание',
    'scheduleSubtitle': 'Еженедельные Zoom‑созвоны в прямом эфире с нашими экспертами. Бесплатно и без регистрации.',
    'scheduleAll': 'Все',
    'scheduleUhr': '',
    'scheduleExpect': 'Что вас ждёт:',
    'scheduleJoinZoom': 'Присоединиться к Zoom',
    'scheduleNoEvents': 'В этой категории нет событий.',
    'backToHub': 'Назад в Hub',
    'askMaria': 'Спросить Марию',
    'pdh.role': 'Founder JetUP',
    'pdh.tagline': 'Финансовые продукты · Партнёрская система · AI-инфраструктура',
    'pdh.btnLive': 'Общаться вживую',
    'pdh.btnChat': 'Написать AI-Денису',
    'pdh.firstMessage': 'Привет! Я — AI-копия Денниса.\n\nМогу за пару минут показать, как устроена система JetUP, или ответить на любой вопрос.\n\nЧто тебе сейчас интереснее?',
    'pdh.startExploration': 'Начать исследование системы',
    'pdh.explorationResponse': 'Отлично.\n\nПокажу систему JetUP за пару минут.\n\nЛистай слайды и нажимай вопросы, если хочешь разобраться глубже.',
    'pdh.followUp': 'Что из этого откликнулось больше всего? Давай разберём твой кейс лично.',
    'pdh.openPresentation': 'Открыть презентацию',
    'pdh.chatPlaceholder': 'Напиши сообщение...',
    'pdh.errorResponse': 'Не удалось получить ответ',
    'pdh.errorConnection': 'Ошибка соединения',
    'pdh.errorPrefix': 'Извини, произошла ошибка: ',
    'pdh.errorShort': 'Ошибка: ',
    'pdh.qr1': 'Пассивный доход',
    'pdh.qr2': 'Партнёрская программа',
    'pdh.qr3': 'Безопасность',
    'pdh.qr4': 'Как начать',
    'pdh.next': 'Далее',
    'pdh.toc': 'Оглавление',
    'pdh.scheduleCall': 'Записаться на звонок',
    'pdh.startLink': 'Начать по моей ссылке',
    'pdh.goTelegram': 'Перейти в Telegram',
    'pdh.viewEcosystem': 'Посмотреть полный обзор экосистемы',
    'pdh.askDennis': 'Спросить Dennis',
    'pdh.ecoAskAbout': 'Расскажи подробнее про',
    'pdh.slideContext': 'Контекст: пользователь смотрит слайд',
    'pdh.slideContextSuffix': 'Ответь на вопрос, опираясь именно на контекст этого слайда. После ответа мягко предложи продолжить презентацию или записаться на созвон.',
    'pdh.s1.title': 'Реальность',
    'pdh.s1.text': 'Рынок финансов растёт.\nИнтерес к пассивному доходу растёт.\n\nНо большинство людей не зарабатывает системно.\n\nПочему?',
    'pdh.s1.c1': 'Почему большинство не зарабатывает?',
    'pdh.s1.c2': 'Какие ошибки делают новички?',
    'pdh.s2.title': 'Диагноз',
    'pdh.s2.text': 'Проблема не в людях. Проблема в модели.\n\nОбычно всё строится на одном сильном лидере, обещаниях и отсутствии системы дубликации.\n\nБез структуры масштаб невозможен.',
    'pdh.s2.c1': 'Почему модель держится на одном лидере?',
    'pdh.s2.c2': 'Что происходит, когда лидер уходит?',
    'pdh.s3.title': 'Модель',
    'pdh.s3.text': 'JetUp — это не «ещё один проект».\n\nЭто соединение финансового продукта, партнёрской модели и инфраструктуры масштабирования в одной системе.',
    'pdh.s3.c1': 'Почему важно соединение трёх элементов?',
    'pdh.s3.c2': 'Что ломается, если одного элемента нет?',
    'pdh.s4.title': 'Безопасность',
    'pdh.s4.text': 'Капитал остаётся на твоём личном аккаунте.\nВерификация на твоё имя.\nТы контролируешь ввод и вывод средств.\n\nКонтроль — у тебя, не у компании.',
    'pdh.s4.i1.label': 'KYC',
    'pdh.s4.i1.desc': 'Полная верификация на твоё имя. Аккаунт принадлежит только тебе.',
    'pdh.s4.i2.label': 'Personal Account',
    'pdh.s4.i2.desc': 'Личный аккаунт у лицензированного брокера. Без посредников.',
    'pdh.s4.i3.label': 'Withdraw Control',
    'pdh.s4.i3.desc': 'Только ты контролируешь вывод средств. Без ограничений.',
    'pdh.s4.c1': 'Где именно хранится капитал?',
    'pdh.s4.c2': 'Кто принимает решение о выводе?',
    'pdh.s5.title': 'Гибкость',
    'pdh.s5.text': 'Нет жёсткой заморозки.\nТы выбираешь стратегию.\nТы можешь менять решения.\n\nЭто управляемая модель.',
    'pdh.s5.i1.label': 'Conservative',
    'pdh.s5.i1.desc': 'Минимальный риск, стабильный доход. Подходит для начинающих.',
    'pdh.s5.i2.label': 'Balanced',
    'pdh.s5.i2.desc': 'Оптимальный баланс риска и доходности. Самый популярный выбор.',
    'pdh.s5.i3.label': 'Aggressive',
    'pdh.s5.i3.desc': 'Максимальная доходность при повышенном риске.',
    'pdh.s5.c1': 'Можно ли поменять стратегию?',
    'pdh.s5.c2': 'Можно ли остановить в любой момент?',
    'pdh.s6.title': 'Рентабельность',
    'pdh.s6.text': 'Мы не строим модель на агрессивных обещаниях.\n\nСистема ориентирована на устойчивость, а не на краткосрочные всплески.\n\nРеалистичный подход сильнее хайпа.',
    'pdh.s6.i1.label': 'Market Cycles',
    'pdh.s6.i1.desc': 'Система адаптируется к рыночным циклам, не завися от одного направления.',
    'pdh.s6.i2.label': 'Risk Management',
    'pdh.s6.i2.desc': 'Встроенное управление рисками ограничивает потери и защищает капитал.',
    'pdh.s6.i3.label': 'Strategy',
    'pdh.s6.i3.desc': 'Долгосрочная стратегия, основанная на данных, а не на эмоциях.',
    'pdh.s6.c1': 'Почему вы не обещаете «иксы»?',
    'pdh.s6.c2': 'Что значит устойчивый подход?',
    'pdh.s7.title': 'Масштаб',
    'pdh.s7.text': 'Даже лучший продукт не масштабируется сам.\n\nПартнёру нужна система, которая позволяет дублицировать действия.\n\nБез инфраструктуры масштаб остаётся идеей.',
    'pdh.s7.c1': 'Что такое «дубликация» на практике?',
    'pdh.s7.c2': 'Почему продукт сам не масштабируется?',
    'pdh.s8.title': 'AI-инфраструктура',
    'pdh.s8.text': 'Каждый партнёр получает цифровую систему:\nAI-чат, интерактивную мини-презентацию, квалификацию лидов и поддержку 24/7.\n\nСистема работает за тебя, пока ты спишь.\nОна презентует, объясняет и фильтрует интерес.\n\nЭто позволяет дублицировать себя.',
    'pdh.s8.i1.label': 'AI Chat',
    'pdh.s8.i1.desc': 'Умный чат-бот отвечает на вопросы клиентов 24/7 от имени партнёра.',
    'pdh.s8.i2.label': 'Mini Presentation',
    'pdh.s8.i2.desc': 'Интерактивная презентация системы — клиент изучает всё сам.',
    'pdh.s8.i3.label': 'Lead Qualification',
    'pdh.s8.i3.desc': 'AI квалифицирует интерес и передаёт только горячие лиды.',
    'pdh.s8.i4.label': '24/7 Support',
    'pdh.s8.i4.desc': 'Автоматическая поддержка работает без перерывов и выходных.',
    'pdh.s8.c1': 'Что AI делает вместо партнёра?',
    'pdh.s8.c2': 'Как AI квалифицирует людей?',
    'pdh.s8.c3': 'Как это выглядит вживую?',
    'pdh.s9.title': 'Экосистема JetUP',
    'pdh.s9.text': 'Единая инфраструктура: брокер, биржа, карта, AI-система и партнёрская сеть — всё связано в одну экосистему.',
    'pdh.s9.c1': 'Как всё связано между собой?',
    'pdh.s9.c2': 'Что даёт экосистема партнёру?',
    'pdh.s10.title': 'Выбор',
    'pdh.s10.text': 'Ты можешь просто изучать информацию.\n\nИли выстроить стратегию правильно с первого шага.\n\nЯ помогу определить формат участия под твой опыт и цели.',
    'pdh.eco.tag': 'TAG Markets',
    'pdh.eco.tagDesc': 'Лицензированная брокерская инфраструктура для доступа к мировым финансовым рынкам.',
    'pdh.eco.bit1': 'BIT1',
    'pdh.eco.bit1Desc': 'Криптобиржа институционального уровня с глубокой ликвидностью.',
    'pdh.eco.bix': 'BIX Card',
    'pdh.eco.bixDesc': 'Криптодебетовая карта нового поколения для мгновенных расходов.',
    'pdh.eco.ai': 'AI System',
    'pdh.eco.aiDesc': 'AI-инфраструктура для автоматизации партнёров и квалификации лидов.',
    'pdh.eco.partners': 'Partners',
    'pdh.eco.partnersDesc': 'Глобальное партнёрское сообщество и многоуровневая экосистема роста.',
    'pdh.explored': 'Изучено',
    'pdh.nextSlide': 'Далее:',
    'pdh.exploreSystem': 'Исследовать систему',
    'pdh.exploreMap': 'Карта JetUP',
    'pdh.explored.trading': 'Трейдинг',
    'pdh.explored.ai': 'AI',
    'pdh.explored.partner': 'Партнёры',
    'pdh.explored.ecosystem': 'Экосистема',
    'pdh.explored.incentives': 'Мотивация',
    'pdh.insight.s3': 'Большинство партнёров пытаются масштабировать продукт. Я масштабирую систему.',
    'pdh.insight.s5': 'Гибкость — это не слабость. Это возможность адаптироваться к любой ситуации.',
    'pdh.insight.s6': 'Устойчивый рост всегда побеждает агрессивные обещания.',
    'pdh.insight.s8': 'AI — не замена партнёру. AI — это мультипликатор его эффективности.',
    'pdh.dennisInsight': 'Dennis insight',
    'pdh.withoutAI': 'Без AI',
    'pdh.withAI': 'С AI',
    'pdh.noai.1': 'Партнёр отвечает на сообщения',
    'pdh.noai.2': 'Партнёр делает звонки',
    'pdh.noai.3': 'Партнёр объясняет презентацию',
    'pdh.noai.4': 'Партнёр повторяет одни и те же ответы',
    'pdh.withai.1': 'AI отвечает 24/7',
    'pdh.withai.2': 'AI квалифицирует лиды',
    'pdh.withai.3': 'AI проводит презентацию',
    'pdh.withai.4': 'Партнёр общается только с серьёзными людьми',
    'pdh.tryDennisAI': 'Попробуй Dennis AI',
    'pdh.aiDemo.q1': 'Сколько можно заработать?',
    'pdh.aiDemo.q2': 'Как работает copy trading?',
    'pdh.aiDemo.q3': 'Можно ли начать с $500?',
    'pdh.pipeline.step1': 'Посетитель приходит',
    'pdh.pipeline.step2': 'AI начинает разговор',
    'pdh.pipeline.step3': 'Квалификация лида',
    'pdh.pipeline.step4': 'Запись на встречу',
    'pdh.engine.title': 'THE JETUP ENGINE',
    'pdh.engine.products': 'Продукты',
    'pdh.engine.ai': 'AI Инфраструктура',
    'pdh.engine.partners': 'Партнёрская система',
    'pdh.engine.result': 'Scaling Engine',
  },
  de: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub: Trading‑ und Partnereinkommen — strukturiert und transparent.',
    'home.tagline': 'Struktur. Transparenz. Kontrolle.',
    'home.mariaOnline': 'Maria – Live‑Beraterin',
    'home.askMaria': 'Maria fragen',
    'home.online': 'online',
    'home.video': 'Video',
    'home.chat': 'Chat',
    'home.trading': 'Trading & Strategien',
    'home.partner': 'Partnerprogramm & Einkommen',
    'home.promo': 'Aktionen',
    'home.schedule': 'Webinare & Termine',
    'home.tutorials': 'Tutorials & Guides',
    'home.directLinks': 'Direktlinks',
    'home.presentations': 'Präsentationen',
    'home.telegram': 'Telegram‑Kanal',
    'home.instagram': 'Instagram',
    'trading.title': 'Trading & Strategien',
    'trading.subtitle': 'Dein Trading‑Bereich: Broker, Copy‑Trading (Copy‑X) и Amplify 12x — an einem Ort.',
    'trading.tagMarkets': 'TAG Markets Broker',
    'trading.tagMarketsSubtitle': 'Regulierte Multi‑Asset‑Brokerage‑Lösung mit MT5.',
    'trading.regulation': 'Regulierung:',
    'trading.regulationDesc': 'Lizenziert durch die FSC Mauritius (Lizenz GB21026474).',
    'trading.conditions': 'Konditionen:',
    'trading.conditionsDesc': 'Max. Hebel 1:500. Über 400 Instrumente.',
    'trading.payouts': 'Auszahlungen:',
    'trading.payoutsDesc': 'Auszahlungen im Durchschnitt innerhalb von 24 Stunden.',
    'trading.scale': 'Skalierung:',
    'trading.scaleDesc': 'Über 500.000 Trader weltweit; monatliches Handelsvolumen über 200 Mrd. USD.',
    'trading.security': 'Sicherheit:',
    'trading.securityDesc': 'Daten‑ и Kapitalschutz nach Bankenstandards. Dein Geld bleibt auf deinem Konto.',
    'trading.copyX': 'Copy‑X Strategien',
    'trading.copyXSubtitle': 'Automatisches Copy‑Trading als potenzielle passive Einkommensquelle.',
    'trading.copyXDesc': 'Kopiere automatisch Profi‑Strategien. Du behältst 70% des Gewinns.',
    'trading.stats': 'Statistiken:',
    'trading.statsDesc': 'Transparente Performance‑Daten für jede Strategie.',
    'trading.control': 'Kontrolle:',
    'trading.controlDesc': 'Jederzeit deaktivierbar. Dein Geld bleibt auf deinem Konto.',
    'trading.risk': 'Risikomanagement:',
    'trading.riskDesc': 'Konservativer Ansatz: max. 10% Drawdown и 0,3% Risiko pro Trade.',
    'trading.vortex': 'Vortex Strategie',
    'trading.vortexSubtitle': 'Demnächst · exklusiv für die JetUP‑Community',
    'trading.vortexComing': 'Demnächst verfügbar — exklusiv für die JetUP‑Community.',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Skaliere dein Eigenkapital um bis zu 12x.',
    'trading.amplifyDesc': 'Amplify ist die Möglichkeit, dein Handelslimit beim Broker zu erhöhen — sofern du die Risikomanagement‑Regeln einhältst.',
    'trading.amplify12x': '12x Skalierung:',
    'trading.amplify12xDesc': 'Mit 1.000 USD Eigenkapital erhältst du 12.000 USD Handelskapital.',
    'trading.liquidity': 'Echte Liquidität:',
    'trading.liquidityDesc': 'Kein Prop‑Firm‑Modell — du handelst am echten Markt.',
    'trading.profit': '100% Profit:',
    'trading.profitDesc': 'Alle Gewinne gehören dir и können jederzeit ausgezahlt werden.',
    'trading.noCredit': 'Kein Kredit:',
    'trading.noCreditDesc': 'Kein Bonus, keine Drittparteien — volle Kontrolle.',
    'trading.start': 'Schnellstart в 5 Schritten',
    'trading.startSubtitle': 'Von der Registrierung bis zum ersten Trade.',
    'trading.startStep1': '1. Registrierung:',
    'trading.startStep1Desc': 'Erstelle ein Konto im JetUP IB Portal.',
    'trading.startStep2': '2. Verbindung:',
    'trading.startStep2Desc': 'Registriere dich beim Partner‑Broker TAG Markets.',
    'trading.startStep3': '3. Installation:',
    'trading.startStep3Desc': 'Lade den MetaTrader 5 herunter и installiere die App.',
    'trading.startStep4': '4. Einzahlung:',
    'trading.startStep4Desc': 'Lade dein Handelskonto beim Broker auf (min. 100 USD).',
    'trading.startStep5': '5. Zugang:',
    'trading.startStep5Desc': 'Erhalte Zugang zu Copy‑X, Signalen и Schulungen.',
    'trading.faq': 'FAQ zu Trading & TAG Markets',
    'trading.faqSubtitle': 'Häufige Fragen auf einen Blick.',
    'trading.faqQ1': 'Ist mein Geld sicher?',
    'trading.faqA1': 'Ja. Dein Geld liegt auf deinem eigenen Konto bei TAG Markets. Nur du hast Zugriff. Auszahlungen sind jederzeit möglich.',
    'trading.faqQ2': 'Wie viel muss ich investieren?',
    'trading.faqA2': 'Minimum 100 USD als Kunde, 250 USD, wenn du auch Partner werden möchtest.',
    'trading.faqQ3': 'Wie hoch ist das Risiko?',
    'trading.faqA3': 'Konservativer Ansatz: max. 0,3% pro Trade и max. 10% Drawdown. Keine Garantien — aber klar definierte Regeln.',
    'trading.faqQ4': 'Wie viel kann ich verdienen?',
    'trading.faqA4': 'Copy‑X Strategien zielen oft auf 2–5% pro Monat ab. Ergebnisse variieren; keine Garantien.',
    'partner.title': 'Partnerprogramm & Einkommen',
    'partner.subtitle': 'Verdiene an realem Handelsvolumen: Provisionen, Profit Share, Infinity Bonus и Global Pools — plus Lifestyle‑Belohnungen.',
    'partner.toolkit': 'Dein Partner‑Toolkit',
    'partner.toolkitSubtitle': 'Tools, Schulung и AI‑Power für deinen Erfolg.',
    'partner.education': 'Schulung & Wissen:',
    'partner.educationDesc': 'Zugang zu Webinaren, Tutorials и Trainings — vom Einstieg bis zum Experten‑Level.',
    'partner.community': 'Community & Support:',
    'partner.communityDesc': 'Aktive Telegram‑Gruppe, persönliche Ansprechpartner и Team‑Calls für den Austausch.',
    'partner.aiTools': 'AI‑Instrumente:',
    'partner.aiToolsDesc': 'Als Partner kannst du deinen eigenen personalisierten Digital Hub mit einer AI‑Beraterin (wie Maria) erhalten — ein smartes Tool für dich, dein Team и deine Kunden.',
    'partner.highlight': 'Genau das, was du hier siehst — dieser Digital Hub — kann für jeden JetUP‑Partner и sein Team personalisiert werden.',
    'partner.commissions': 'Lot‑Provisionen',
    'partner.commissionsSubtitle': 'Verdienst pro gehandeltem Lot in deinem Team.',
    'partner.amount': 'Du erhältst 10,50 USD pro gehandeltem Lot in deinem Team.',
    'partner.levels': 'Bis zu 10 Ebenen tief — je aktiver dein Team, desto mehr kannst du verdienen.',
    'partner.basis': 'Alle Provisionen basieren auf realem Handelsvolumen — nicht auf Einzahlungen.',
    'partner.profitShare': 'Profit Share vom Team',
    'partner.profitShareSubtitle': 'Beteiligung an realen Handelsergebnissen.',
    'partner.share': 'Du erhältst einen Anteil an den realen Handelsergebnissen deines Teams.',
    'partner.distribution': 'Gewinnverteilung: 70% Kunde, 30% werden zwischen Tradern и der Partnerstruktur verteilt.',
    'partner.profitBasis': 'Auszahlungen basieren auf echten Gewinnen — nicht auf Versprechen.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Extra‑Prozente bei wachsendem Teamvolumen.',
    'partner.infinityDesc': 'Zusätzlicher Bonus‑Prozentsatz, sobald bestimmte Schwellenwerte beim Teamvolumen erreicht werden:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'ab 100.000 EUR Volumen',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'ab 300.000 EUR Volumen',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'ab 1.000.000 EUR Volumen',
    'partner.infinityStep4': 'Bis zu +5% bei Teamvolumen von 100k bis 20M USD',
    'partner.rewards': 'Global Pools & Lifestyle‑Belohnungen',
    'partner.rewardsSubtitle': 'Rolex, Immobilien, Reisen и mehr.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Zwei Pools mit jeweils 1% des Unternehmensgewinns. Auszahlung alle zwei Wochen.',
    'partner.lifestyleTitle': 'Lifestyle‑Belohnungen:',
    'partner.lifestyle1': 'Rolex‑Uhren ab 500k USD Teamvolumen',
    'partner.lifestyle2': 'Immobilien‑Gutscheine bis zu 1.200.000 USD',
    'partner.lifestyle3': 'Exklusive Reisen (z. B. Bali, Türkei)',
    'partner.pdf': 'Partner PDF / Präsentation',
    'tutorials.title': 'Tutorials & Guides',
    'tutorials.subtitle': 'Kurze Videos и Schritt‑für‑Schritt‑Anleitungen zum Trading и Partnerprogramm.',
    'tutorials.all': 'Alle',
    'tutorials.forTraders': 'Für Trader',
    'tutorials.forPartners': 'Für Partner',
    'promo.title': 'Aktionen & Angebote',
    'promo.noPromos': 'Aktuell sind keine Aktionen verfügbar.',
    'common.back': 'Zurück',
    'common.backToHub': 'Zurück zum Hub',
    'common.askMaria': 'Maria fragen',
    'common.comingSoon': 'Demnächst',
    'common.video': 'Video',
    'common.guide': 'Guide',
    'common.min': 'Min.',
    'nav.home': 'Home',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Chat',
    'nav.application': 'Anfragen',
    'chat.maria': 'Maria',
    'chat.online': 'Online',
    'chat.placeholder': 'Nachricht schreiben...',
    'chat.greeting': 'Hallo! Ich bin Maria, die JetUP‑Assistentin. Ich erzähle dir alles über das Ökosystem и helfe dir, dich zurechtzufinden. Was interessiert dich?',
    'chat.typing': 'Maria schreibt...',
    'video.startCall': 'Videoanruf mit Maria',
    'video.endCall': 'Beenden',
    'video.connecting': 'Verbindung...',
    'app.title': 'Beratungsanfrage',
    'app.name': 'Dein Name',
    'app.phone': 'Telefon',
    'app.email': 'E‑Mail',
    'app.submit': 'Anfrage senden',
    'app.success': 'Anfrage gesendet!',
    'jetup.title': 'JetUP Ökosystem',
    'jetup.desc': 'Eine moderne Plattform für den Zugang zu den Finanzmärkten',
    'jetup.copyTrading': 'Copy‑X Strategien',
    'jetup.copyTradingDesc': 'Automatisches Kopieren von Profi‑Strategien mit voller Kontrolle',
    'jetup.signals': 'Trading‑Signale',
    'jetup.signalsDesc': 'Echtzeit‑Signale mit präzisen Einstiegspunkten и Analysen',
    'jetup.academy': 'JetUP Akademie',
    'jetup.academyDesc': 'Ausbildung в Trading, Risikomanagement и Systemdenken',
    'jetup.partner': 'Partnerprogramm',
    'jetup.partnerDesc': 'Strukturierte Einkommensmodelle basierend auf realem Handelsvolumen',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Lizenzierter Broker — dein Kapital bleibt immer auf deinem Konto',
    'jetup.howToStart': 'Wie starten?',
    'jetup.startDesc': 'Registrierung → TAG Markets → MetaTrader 5 → Einzahlung → Zugang zu Tools',
    'jetup.minClient': 'Minimum für Kunden: 100 USD',
    'jetup.minPartner': 'Minimum für Partner: 250 USD',
    'scheduleTitle': 'Webinare & Termine',
    'scheduleSubtitle': 'Wöchentliche Zoom‑Live‑Calls mit unseren Experten. Kostenlos и ohne Anmeldung.',
    'scheduleAll': 'Alle',
    'scheduleUhr': 'Uhr',
    'scheduleExpect': 'Was dich erwartet:',
    'scheduleJoinZoom': 'Zoom beitreten',
    'scheduleNoEvents': 'Keine Termine в dieser Kategorie.',
    'backToHub': 'Zurück zum Hub',
    'askMaria': 'Maria fragen',
    'pdh.role': 'Founder JetUP',
    'pdh.tagline': 'Finanzprodukte · Partnersystem · AI-Infrastruktur',
    'pdh.btnLive': 'Live sprechen',
    'pdh.btnChat': 'AI-Dennis schreiben',
    'pdh.firstMessage': 'Hallo! Ich bin die AI-Kopie von Dennis.\n\nIch kann dir in wenigen Minuten zeigen, wie das JetUP-System funktioniert, oder jede Frage beantworten.\n\nWas interessiert dich gerade mehr?',
    'pdh.startExploration': 'System erkunden',
    'pdh.explorationResponse': 'Super.\n\nIch zeige dir das JetUP-System in wenigen Minuten.\n\nBlättere durch die Slides und tippe auf Fragen, wenn du tiefer einsteigen willst.',
    'pdh.followUp': 'Was davon hat dich am meisten angesprochen? Lass uns deinen Fall persönlich besprechen.',
    'pdh.openPresentation': 'Präsentation öffnen',
    'pdh.chatPlaceholder': 'Nachricht schreiben...',
    'pdh.errorResponse': 'Antwort konnte nicht abgerufen werden',
    'pdh.errorConnection': 'Verbindungsfehler',
    'pdh.errorPrefix': 'Entschuldigung, ein Fehler ist aufgetreten: ',
    'pdh.errorShort': 'Fehler: ',
    'pdh.qr1': 'Passives Einkommen',
    'pdh.qr2': 'Partnerprogramm',
    'pdh.qr3': 'Sicherheit',
    'pdh.qr4': 'Wie starten',
    'pdh.next': 'Weiter',
    'pdh.toc': 'Inhaltsverzeichnis',
    'pdh.scheduleCall': 'Gespräch buchen',
    'pdh.startLink': 'Über meinen Link starten',
    'pdh.goTelegram': 'Zu Telegram wechseln',
    'pdh.viewEcosystem': 'Komplettes Ökosystem ansehen',
    'pdh.askDennis': 'Dennis fragen',
    'pdh.ecoAskAbout': 'Erzähl mir mehr über',
    'pdh.slideContext': 'Kontext: der Nutzer schaut Slide',
    'pdh.slideContextSuffix': 'Beantworte die Frage basierend auf dem Kontext dieses Slides. Schlage danach sanft vor, die Präsentation fortzusetzen oder ein Gespräch zu vereinbaren.',
    'pdh.s1.title': 'Realität',
    'pdh.s1.text': 'Der Finanzmarkt wächst.\nDas Interesse an passivem Einkommen steigt.\n\nAber die meisten Menschen verdienen nicht systematisch.\n\nWarum?',
    'pdh.s1.c1': 'Warum verdienen die meisten nicht?',
    'pdh.s1.c2': 'Welche Fehler machen Anfänger?',
    'pdh.s2.title': 'Diagnose',
    'pdh.s2.text': 'Das Problem sind nicht die Menschen. Das Problem ist das Modell.\n\nNormalerweise basiert alles auf einem starken Leader, Versprechen und fehlender Duplikation.\n\nOhne Struktur ist Skalierung unmöglich.',
    'pdh.s2.c1': 'Warum hängt das Modell an einem Leader?',
    'pdh.s2.c2': 'Was passiert, wenn der Leader geht?',
    'pdh.s3.title': 'Modell',
    'pdh.s3.text': 'JetUp ist nicht „noch ein Projekt".\n\nEs ist die Verbindung von Finanzprodukt, Partnermodell und Skalierungsinfrastruktur in einem System.',
    'pdh.s3.c1': 'Warum ist die Verbindung der drei Elemente wichtig?',
    'pdh.s3.c2': 'Was bricht zusammen, wenn ein Element fehlt?',
    'pdh.s4.title': 'Sicherheit',
    'pdh.s4.text': 'Dein Kapital bleibt auf deinem persönlichen Konto.\nVerifizierung auf deinen Namen.\nDu kontrollierst Ein- und Auszahlungen.\n\nDie Kontrolle liegt bei dir, nicht beim Unternehmen.',
    'pdh.s4.i1.label': 'KYC',
    'pdh.s4.i1.desc': 'Vollständige Verifizierung auf deinen Namen. Das Konto gehört nur dir.',
    'pdh.s4.i2.label': 'Persönliches Konto',
    'pdh.s4.i2.desc': 'Persönliches Konto bei einem lizenzierten Broker. Ohne Zwischenhändler.',
    'pdh.s4.i3.label': 'Auszahlungskontrolle',
    'pdh.s4.i3.desc': 'Nur du kontrollierst Auszahlungen. Ohne Einschränkungen.',
    'pdh.s4.c1': 'Wo genau wird das Kapital verwahrt?',
    'pdh.s4.c2': 'Wer entscheidet über Auszahlungen?',
    'pdh.s5.title': 'Flexibilität',
    'pdh.s5.text': 'Keine starre Sperrfrist.\nDu wählst die Strategie.\nDu kannst Entscheidungen ändern.\n\nEs ist ein steuerbares Modell.',
    'pdh.s5.i1.label': 'Konservativ',
    'pdh.s5.i1.desc': 'Minimales Risiko, stabiles Einkommen. Ideal für Einsteiger.',
    'pdh.s5.i2.label': 'Ausgewogen',
    'pdh.s5.i2.desc': 'Optimale Balance zwischen Risiko und Rendite. Die beliebteste Wahl.',
    'pdh.s5.i3.label': 'Aggressiv',
    'pdh.s5.i3.desc': 'Maximale Rendite bei erhöhtem Risiko.',
    'pdh.s5.c1': 'Kann man die Strategie wechseln?',
    'pdh.s5.c2': 'Kann man jederzeit aufhören?',
    'pdh.s6.title': 'Rentabilität',
    'pdh.s6.text': 'Wir bauen kein Modell auf aggressiven Versprechen.\n\nDas System ist auf Nachhaltigkeit ausgerichtet, nicht auf kurzfristige Spitzen.\n\nEin realistischer Ansatz ist stärker als Hype.',
    'pdh.s6.i1.label': 'Marktzyklen',
    'pdh.s6.i1.desc': 'Das System passt sich an Marktzyklen an, ohne von einer Richtung abhängig zu sein.',
    'pdh.s6.i2.label': 'Risikomanagement',
    'pdh.s6.i2.desc': 'Integriertes Risikomanagement begrenzt Verluste und schützt das Kapital.',
    'pdh.s6.i3.label': 'Strategie',
    'pdh.s6.i3.desc': 'Langfristige Strategie basierend auf Daten, nicht auf Emotionen.',
    'pdh.s6.c1': 'Warum versprecht ihr keine „X-fachen" Renditen?',
    'pdh.s6.c2': 'Was bedeutet nachhaltiger Ansatz?',
    'pdh.s7.title': 'Skalierung',
    'pdh.s7.text': 'Auch das beste Produkt skaliert nicht von selbst.\n\nEin Partner braucht ein System, das es ermöglicht, Aktionen zu duplizieren.\n\nOhne Infrastruktur bleibt Skalierung eine Idee.',
    'pdh.s7.c1': 'Was bedeutet „Duplikation" in der Praxis?',
    'pdh.s7.c2': 'Warum skaliert das Produkt nicht von selbst?',
    'pdh.s8.title': 'AI-Infrastruktur',
    'pdh.s8.text': 'Jeder Partner bekommt ein digitales System:\nAI-Chat, interaktive Mini-Präsentation, Lead-Qualifizierung und 24/7-Support.\n\nDas System arbeitet für dich, während du schläfst.\nEs präsentiert, erklärt und filtert Interesse.\n\nDas ermöglicht es, sich selbst zu duplizieren.',
    'pdh.s8.i1.label': 'AI Chat',
    'pdh.s8.i1.desc': 'Intelligenter Chatbot beantwortet Kundenfragen 24/7 im Namen des Partners.',
    'pdh.s8.i2.label': 'Mini-Präsentation',
    'pdh.s8.i2.desc': 'Interaktive Systempräsentation — der Kunde lernt alles selbst.',
    'pdh.s8.i3.label': 'Lead-Qualifizierung',
    'pdh.s8.i3.desc': 'AI qualifiziert Interesse und übergibt nur heiße Leads.',
    'pdh.s8.i4.label': '24/7 Support',
    'pdh.s8.i4.desc': 'Automatischer Support arbeitet ohne Pausen und Wochenenden.',
    'pdh.s8.c1': 'Was macht die AI anstelle des Partners?',
    'pdh.s8.c2': 'Wie qualifiziert die AI Menschen?',
    'pdh.s8.c3': 'Wie sieht das live aus?',
    'pdh.s9.title': 'JetUP Ökosystem',
    'pdh.s9.text': 'Eine einheitliche Infrastruktur: Broker, Börse, Karte, AI-System und Partnernetzwerk — alles in einem Ökosystem verbunden.',
    'pdh.s9.c1': 'Wie hängt alles zusammen?',
    'pdh.s9.c2': 'Was bringt das Ökosystem dem Partner?',
    'pdh.s10.title': 'Deine Wahl',
    'pdh.s10.text': 'Du kannst einfach Informationen studieren.\n\nOder von Anfang an die richtige Strategie aufbauen.\n\nIch helfe dir, das passende Teilnahmeformat für deine Erfahrung und Ziele zu finden.',
    'pdh.eco.tag': 'TAG Markets',
    'pdh.eco.tagDesc': 'Lizenzierte Broker-Infrastruktur für den Zugang zu globalen Finanzmärkten.',
    'pdh.eco.bit1': 'BIT1',
    'pdh.eco.bit1Desc': 'Krypto-Börse auf institutionellem Niveau mit tiefer Liquidität.',
    'pdh.eco.bix': 'BIX Card',
    'pdh.eco.bixDesc': 'Krypto-Debitkarte der nächsten Generation für nahtloses Bezahlen.',
    'pdh.eco.ai': 'AI System',
    'pdh.eco.aiDesc': 'AI-Infrastruktur für Partner-Automatisierung und Lead-Qualifizierung.',
    'pdh.eco.partners': 'Partners',
    'pdh.eco.partnersDesc': 'Globale Partner-Community und mehrstufiges Ökosystem für gemeinsames Wachstum.',
    'pdh.explored': 'Erkundet',
    'pdh.nextSlide': 'Weiter:',
    'pdh.exploreSystem': 'System erkunden',
    'pdh.exploreMap': 'JetUP Karte',
    'pdh.explored.trading': 'Trading',
    'pdh.explored.ai': 'AI',
    'pdh.explored.partner': 'Partner',
    'pdh.explored.ecosystem': 'Ökosystem',
    'pdh.explored.incentives': 'Anreize',
    'pdh.insight.s3': 'Die meisten Partner versuchen ein Produkt zu skalieren. Ich skaliere ein System.',
    'pdh.insight.s5': 'Flexibilität ist keine Schwäche. Es ist die Fähigkeit, sich anzupassen.',
    'pdh.insight.s6': 'Nachhaltiges Wachstum schlägt immer aggressive Versprechen.',
    'pdh.insight.s8': 'AI ersetzt nicht den Partner. AI ist ein Multiplikator seiner Effizienz.',
    'pdh.dennisInsight': 'Dennis insight',
    'pdh.withoutAI': 'Ohne AI',
    'pdh.withAI': 'Mit AI',
    'pdh.noai.1': 'Partner beantwortet Nachrichten',
    'pdh.noai.2': 'Partner führt Anrufe',
    'pdh.noai.3': 'Partner erklärt die Präsentation',
    'pdh.noai.4': 'Partner wiederholt dieselben Antworten',
    'pdh.withai.1': 'AI antwortet 24/7',
    'pdh.withai.2': 'AI qualifiziert Leads',
    'pdh.withai.3': 'AI führt die Präsentation',
    'pdh.withai.4': 'Partner spricht nur mit ernsthaften Interessenten',
    'pdh.tryDennisAI': 'Dennis AI ausprobieren',
    'pdh.aiDemo.q1': 'Wie viel kann man verdienen?',
    'pdh.aiDemo.q2': 'Wie funktioniert Copy Trading?',
    'pdh.aiDemo.q3': 'Kann man mit 500€ starten?',
    'pdh.pipeline.step1': 'Besucher kommt',
    'pdh.pipeline.step2': 'AI startet Gespräch',
    'pdh.pipeline.step3': 'Lead-Qualifizierung',
    'pdh.pipeline.step4': 'Termin buchen',
    'pdh.engine.title': 'THE JETUP ENGINE',
    'pdh.engine.products': 'Produkte',
    'pdh.engine.ai': 'AI-Infrastruktur',
    'pdh.engine.partners': 'Partnersystem',
    'pdh.engine.result': 'Scaling Engine',
  },
  en: {
    'home.title': 'JetUP',
    'home.subtitle': 'JetUP Digital Hub — trading and partner income with structure and transparency.',
    'home.tagline': 'Structure. Transparency. Control.',
    'home.mariaOnline': 'Maria — Live Consultant',
    'home.askMaria': 'Ask Maria',
    'home.online': 'online',
    'home.video': 'Video',
    'home.chat': 'Chat',
    'home.trading': 'Trading & Strategies',
    'home.partner': 'Partner Program & Income',
    'home.promo': 'Promotions',
    'home.schedule': 'Webinars & Schedule',
    'home.tutorials': 'Tutorials & Guides',
    'home.directLinks': 'Quick Links',
    'home.presentations': 'Presentations',
    'home.telegram': 'Telegram Channel',
    'home.instagram': 'Instagram',
    'trading.title': 'Trading & Strategies',
    'trading.subtitle': 'Your trading hub: broker, copy trading (Copy‑X), and Amplify 12x — all in one place.',
    'trading.tagMarkets': 'TAG Markets Broker',
    'trading.tagMarketsSubtitle': 'Regulated multi-asset brokerage solution with MT5.',
    'trading.regulation': 'Regulation:',
    'trading.regulationDesc': 'Licensed by FSC Mauritius (license GB21026474).',
    'trading.conditions': 'Conditions:',
    'trading.conditionsDesc': 'Max. leverage 1:500. Over 400 instruments.',
    'trading.payouts': 'Payouts:',
    'trading.payoutsDesc': 'Withdrawals processed on average within 24 hours.',
    'trading.scale': 'Scale:',
    'trading.scaleDesc': 'Over 500,000 traders worldwide; monthly trading volume exceeding $200 billion.',
    'trading.security': 'Security:',
    'trading.securityDesc': 'Bank-grade data and capital protection. Your funds stay in your account.',
    'trading.copyX': 'Copy‑X Strategies',
    'trading.copyXSubtitle': 'Automated copy trading as a more "passive" participation option.',
    'trading.copyXDesc': 'Automatically copy professional strategies. You keep 70% of the profit.',
    'trading.stats': 'Statistics:',
    'trading.statsDesc': 'Transparent performance data for each strategy.',
    'trading.control': 'Control:',
    'trading.controlDesc': 'Can be deactivated at any time. Your funds stay in your account.',
    'trading.risk': 'Risk Management:',
    'trading.riskDesc': 'Conservative approach: max. 10% drawdown, 0.3% risk per trade.',
    'trading.vortex': 'Vortex Strategy',
    'trading.vortexSubtitle': 'Coming Soon · exclusively for the JetUP community',
    'trading.vortexComing': 'Coming soon — exclusively for the JetUP community!',
    'trading.amplify': 'Amplify 12x',
    'trading.amplifySubtitle': 'Scale your own capital up to 12x.',
    'trading.amplifyDesc': 'Amplify lets you increase your trading limit with the broker while following risk management rules.',
    'trading.amplify12x': '12x:',
    'trading.amplify12xDesc': 'With $1,000 of your own, you get $12,000 in trading capital.',
    'trading.liquidity': 'Liquidity:',
    'trading.liquidityDesc': 'Not a prop firm model — you trade on the real market.',
    'trading.profit': 'Profit:',
    'trading.profitDesc': 'All profits belong to you, withdrawals available at any time.',
    'trading.noCredit': 'No Credit:',
    'trading.noCreditDesc': 'No bonuses, no third parties. Full control.',
    'trading.start': 'Quick Start in 5 Steps',
    'trading.startSubtitle': 'From registration to your first trade.',
    'trading.startStep1': '1. Registration:',
    'trading.startStep1Desc': 'Create an account on the JetUP IB Portal.',
    'trading.startStep2': '2. Connection:',
    'trading.startStep2Desc': 'Register with the partner broker TAG Markets.',
    'trading.startStep3': '3. Installation:',
    'trading.startStep3Desc': 'Download and install MetaTrader 5.',
    'trading.startStep4': '4. Deposit:',
    'trading.startStep4Desc': 'Fund your trading account with the broker (min. $100).',
    'trading.startStep5': '5. Access:',
    'trading.startStep5Desc': 'Get access to Copy‑X, signals, and training.',
    'trading.faq': 'Trading & TAG Markets FAQ',
    'trading.faqSubtitle': 'Frequently asked questions.',
    'trading.faqQ1': 'Is my money safe?',
    'trading.faqA1': 'Yes. Your money is in your own account at TAG Markets. Only you have access. Withdrawals are available at any time.',
    'trading.faqQ2': 'How much do I need to invest?',
    'trading.faqA2': 'Minimum $100 as a client, $250 if you also want to become a partner.',
    'trading.faqQ3': 'What is the risk level?',
    'trading.faqA3': 'Conservative: max. 0.3% per trade, max. 10% drawdown. No guarantees, but the risk is controlled.',
    'trading.faqQ4': 'How much can I earn?',
    'trading.faqA4': '2–5% per month with Copy‑X strategies. Results may vary; no guarantees.',
    'partner.title': 'Partner Program & Income',
    'partner.subtitle': 'Income based on real trading volume: commissions, Profit Share, Infinity Bonus, and Global Pools — plus lifestyle rewards.',
    'partner.toolkit': 'Your Partner Toolkit',
    'partner.toolkitSubtitle': 'Tools, training, and AI support for your growth.',
    'partner.education': 'Education & Knowledge:',
    'partner.educationDesc': 'Access to webinars, tutorials, and training — from beginner to advanced level.',
    'partner.community': 'Community & Support:',
    'partner.communityDesc': 'Active Telegram group, personal contacts, and team calls.',
    'partner.aiTools': 'AI Tools:',
    'partner.aiToolsDesc': 'Every partner can get a personalized Digital Hub with their own AI consultant (like Maria) — a smart tool for your team and clients.',
    'partner.highlight': 'What you see right now — this Digital Hub — can be personalized for every JetUP partner and their team.',
    'partner.commissions': 'Lot Commissions',
    'partner.commissionsSubtitle': 'Earnings for every lot traded in your team.',
    'partner.amount': 'You earn $10.50 for every lot traded in your team.',
    'partner.levels': 'Up to 10 levels deep — the more active your team, the higher your income.',
    'partner.basis': 'All commissions are based on real trading volume, not on deposits.',
    'partner.profitShare': 'Team Profit Share',
    'partner.profitShareSubtitle': 'Share of trading results.',
    'partner.share': 'You receive a share of your team\'s real trading results.',
    'partner.distribution': 'Distribution: 70% to the client, 30% is split between traders and the partner program structure.',
    'partner.profitBasis': 'Payouts are based on real profits, not on promises.',
    'partner.infinity': 'Infinity Bonus',
    'partner.infinitySubtitle': 'Extra percentages as your team volume grows.',
    'partner.infinityDesc': 'Additional bonus percentage when certain team volume thresholds are reached:',
    'partner.infinityStep1': '1%',
    'partner.infinityStep1Desc': 'from €100,000 volume',
    'partner.infinityStep2': '2%',
    'partner.infinityStep2Desc': 'from €300,000 volume',
    'partner.infinityStep3': '3%',
    'partner.infinityStep3Desc': 'from €1,000,000 volume',
    'partner.infinityStep4': 'Up to +5% with team volume from $100k to $20M',
    'partner.rewards': 'Global Pools & Lifestyle Rewards',
    'partner.rewardsSubtitle': 'Rolex, real estate, travel, and more.',
    'partner.poolsTitle': 'Global Pools:',
    'partner.poolsDesc': 'Two pools of 1% of company profits each. Payouts every two weeks.',
    'partner.lifestyleTitle': 'Lifestyle Rewards:',
    'partner.lifestyle1': 'Rolex watch from $500k team volume',
    'partner.lifestyle2': 'Real estate certificates up to $1,200,000',
    'partner.lifestyle3': 'Exclusive trips (Bali, Turkey)',
    'partner.pdf': 'Partner PDF / Presentation',
    'tutorials.title': 'Tutorials & Guides',
    'tutorials.subtitle': 'Short videos and step-by-step guides on trading and the partner program.',
    'tutorials.all': 'All',
    'tutorials.forTraders': 'For Traders',
    'tutorials.forPartners': 'For Partners',
    'promo.title': 'Promotions & Offers',
    'promo.noPromos': 'No active promotions at this time.',
    'common.back': 'Back',
    'common.backToHub': 'Back to Hub',
    'common.askMaria': 'Ask Maria',
    'common.comingSoon': 'Coming Soon',
    'common.video': 'Video',
    'common.guide': 'Guide',
    'common.min': 'min',
    'quick.whatIsJetup': 'What is JetUP?',
    'quick.howToStart': 'How to get started?',
    'quick.isSafe': 'Is it safe?',
    'nav.home': 'Home',
    'nav.jetup': 'JetUP',
    'nav.chat': 'Chat',
    'nav.application': 'Application',
    'chat.maria': 'Maria',
    'chat.online': 'Online',
    'chat.placeholder': 'Type a message...',
    'chat.greeting': 'Hi! I\'m Maria, the JetUP assistant. I\'ll tell you all about the ecosystem and help you navigate it. What are you interested in?',
    'chat.typing': 'Maria is typing...',
    'video.startCall': 'Video call with Maria',
    'video.endCall': 'End',
    'video.connecting': 'Connecting...',
    'app.title': 'Consultation Request',
    'app.name': 'Your Name',
    'app.phone': 'Phone',
    'app.email': 'Email',
    'app.submit': 'Submit Request',
    'app.success': 'Request submitted!',
    'jetup.title': 'JetUP Ecosystem',
    'jetup.desc': 'A modern platform for accessing the financial markets',
    'jetup.copyTrading': 'Copy‑X Strategies',
    'jetup.copyTradingDesc': 'Automatic copying of professional strategies with full control',
    'jetup.signals': 'Trading Signals',
    'jetup.signalsDesc': 'Real-time signals with precise entry levels and analysis',
    'jetup.academy': 'JetUP Academy',
    'jetup.academyDesc': 'Training in trading, risk management, and system building',
    'jetup.partner': 'Partner Program',
    'jetup.partnerDesc': 'Structured income models based on real trading volume',
    'jetup.tagMarkets': 'TAG Markets',
    'jetup.tagMarketsDesc': 'Licensed broker — your capital always stays in your account',
    'jetup.howToStart': 'How to get started?',
    'jetup.startDesc': 'Registration → TAG Markets → MetaTrader 5 → Deposit → Access to tools',
    'jetup.minClient': 'Minimum for clients: $100',
    'jetup.minPartner': 'Minimum for partners: $250',
    'scheduleTitle': 'Webinars & Schedule',
    'scheduleSubtitle': 'Weekly live Zoom calls with our experts. Free and no registration required.',
    'scheduleAll': 'All',
    'scheduleUhr': '',
    'scheduleExpect': 'What to expect:',
    'scheduleJoinZoom': 'Join Zoom Call',
    'scheduleNoEvents': 'No events in this category.',
    'backToHub': 'Back to Hub',
    'askMaria': 'Ask Maria',
    'pdh.role': 'Founder JetUP',
    'pdh.tagline': 'Financial products · Partner system · AI infrastructure',
    'pdh.btnLive': 'Talk live',
    'pdh.btnChat': 'Write to AI Dennis',
    'pdh.firstMessage': 'Hi! I\'m an AI copy of Dennis.\n\nI can show you how the JetUP system works in a few minutes, or answer any question.\n\nWhat interests you more right now?',
    'pdh.startExploration': 'Explore the system',
    'pdh.explorationResponse': 'Great.\n\nI\'ll show you the JetUP system in a few minutes.\n\nSwipe through the slides and tap questions if you want to dive deeper.',
    'pdh.followUp': 'What resonated with you the most? Let\'s discuss your case personally.',
    'pdh.openPresentation': 'Open presentation',
    'pdh.chatPlaceholder': 'Write a message...',
    'pdh.errorResponse': 'Failed to get a response',
    'pdh.errorConnection': 'Connection error',
    'pdh.errorPrefix': 'Sorry, an error occurred: ',
    'pdh.errorShort': 'Error: ',
    'pdh.qr1': 'Passive income',
    'pdh.qr2': 'Partner program',
    'pdh.qr3': 'Security',
    'pdh.qr4': 'How to start',
    'pdh.next': 'Next',
    'pdh.toc': 'Contents',
    'pdh.scheduleCall': 'Schedule a call',
    'pdh.startLink': 'Start with my link',
    'pdh.goTelegram': 'Go to Telegram',
    'pdh.viewEcosystem': 'View full ecosystem overview',
    'pdh.askDennis': 'Ask Dennis',
    'pdh.ecoAskAbout': 'Tell me more about',
    'pdh.slideContext': 'Context: user is viewing slide',
    'pdh.slideContextSuffix': 'Answer the question based on this slide\'s context. After answering, gently suggest continuing the presentation or scheduling a call.',
    'pdh.s1.title': 'Reality',
    'pdh.s1.text': 'The financial market is growing.\nInterest in passive income is growing.\n\nBut most people don\'t earn systematically.\n\nWhy?',
    'pdh.s1.c1': 'Why don\'t most people earn?',
    'pdh.s1.c2': 'What mistakes do beginners make?',
    'pdh.s2.title': 'Diagnosis',
    'pdh.s2.text': 'The problem isn\'t the people. The problem is the model.\n\nUsually everything relies on one strong leader, promises, and lack of duplication.\n\nWithout structure, scale is impossible.',
    'pdh.s2.c1': 'Why does the model depend on one leader?',
    'pdh.s2.c2': 'What happens when the leader leaves?',
    'pdh.s3.title': 'Model',
    'pdh.s3.text': 'JetUp is not "just another project".\n\nIt\'s the combination of a financial product, partner model, and scaling infrastructure in one system.',
    'pdh.s3.c1': 'Why is the combination of three elements important?',
    'pdh.s3.c2': 'What breaks if one element is missing?',
    'pdh.s4.title': 'Security',
    'pdh.s4.text': 'Your capital stays in your personal account.\nVerification in your name.\nYou control deposits and withdrawals.\n\nControl is with you, not the company.',
    'pdh.s4.i1.label': 'KYC',
    'pdh.s4.i1.desc': 'Full verification in your name. The account belongs only to you.',
    'pdh.s4.i2.label': 'Personal Account',
    'pdh.s4.i2.desc': 'Personal account with a licensed broker. No intermediaries.',
    'pdh.s4.i3.label': 'Withdrawal Control',
    'pdh.s4.i3.desc': 'Only you control withdrawals. No restrictions.',
    'pdh.s4.c1': 'Where exactly is the capital stored?',
    'pdh.s4.c2': 'Who decides on withdrawals?',
    'pdh.s5.title': 'Flexibility',
    'pdh.s5.text': 'No rigid lock-up.\nYou choose the strategy.\nYou can change decisions.\n\nIt\'s a controllable model.',
    'pdh.s5.i1.label': 'Conservative',
    'pdh.s5.i1.desc': 'Minimal risk, stable income. Ideal for beginners.',
    'pdh.s5.i2.label': 'Balanced',
    'pdh.s5.i2.desc': 'Optimal balance of risk and return. The most popular choice.',
    'pdh.s5.i3.label': 'Aggressive',
    'pdh.s5.i3.desc': 'Maximum returns with increased risk.',
    'pdh.s5.c1': 'Can I change the strategy?',
    'pdh.s5.c2': 'Can I stop at any time?',
    'pdh.s6.title': 'Profitability',
    'pdh.s6.text': 'We don\'t build a model on aggressive promises.\n\nThe system is focused on sustainability, not short-term spikes.\n\nA realistic approach is stronger than hype.',
    'pdh.s6.i1.label': 'Market Cycles',
    'pdh.s6.i1.desc': 'The system adapts to market cycles without depending on one direction.',
    'pdh.s6.i2.label': 'Risk Management',
    'pdh.s6.i2.desc': 'Built-in risk management limits losses and protects capital.',
    'pdh.s6.i3.label': 'Strategy',
    'pdh.s6.i3.desc': 'Long-term strategy based on data, not emotions.',
    'pdh.s6.c1': 'Why don\'t you promise huge returns?',
    'pdh.s6.c2': 'What does a sustainable approach mean?',
    'pdh.s7.title': 'Scale',
    'pdh.s7.text': 'Even the best product doesn\'t scale by itself.\n\nA partner needs a system that allows duplicating actions.\n\nWithout infrastructure, scale remains an idea.',
    'pdh.s7.c1': 'What does "duplication" mean in practice?',
    'pdh.s7.c2': 'Why doesn\'t the product scale by itself?',
    'pdh.s8.title': 'AI Infrastructure',
    'pdh.s8.text': 'Every partner gets a digital system:\nAI chat, interactive mini-presentation, lead qualification, and 24/7 support.\n\nThe system works for you while you sleep.\nIt presents, explains, and filters interest.\n\nThis allows you to duplicate yourself.',
    'pdh.s8.i1.label': 'AI Chat',
    'pdh.s8.i1.desc': 'Smart chatbot answers client questions 24/7 on the partner\'s behalf.',
    'pdh.s8.i2.label': 'Mini Presentation',
    'pdh.s8.i2.desc': 'Interactive system presentation — the client learns everything on their own.',
    'pdh.s8.i3.label': 'Lead Qualification',
    'pdh.s8.i3.desc': 'AI qualifies interest and only passes on hot leads.',
    'pdh.s8.i4.label': '24/7 Support',
    'pdh.s8.i4.desc': 'Automatic support works without breaks or days off.',
    'pdh.s8.c1': 'What does AI do instead of the partner?',
    'pdh.s8.c2': 'How does AI qualify people?',
    'pdh.s8.c3': 'What does it look like live?',
    'pdh.s9.title': 'JetUP Ecosystem',
    'pdh.s9.text': 'A unified infrastructure: broker, exchange, card, AI system, and partner network — all connected in one ecosystem.',
    'pdh.s9.c1': 'How is everything connected?',
    'pdh.s9.c2': 'What does the ecosystem give the partner?',
    'pdh.s10.title': 'Your Choice',
    'pdh.s10.text': 'You can simply study the information.\n\nOr build the right strategy from the first step.\n\nI\'ll help you determine the participation format for your experience and goals.',
    'pdh.eco.tag': 'TAG Markets',
    'pdh.eco.tagDesc': 'Licensed brokerage infrastructure for global financial markets access.',
    'pdh.eco.bit1': 'BIT1',
    'pdh.eco.bit1Desc': 'Institutional-grade crypto exchange platform with deep liquidity.',
    'pdh.eco.bix': 'BIX Card',
    'pdh.eco.bixDesc': 'Next-gen crypto debit card for seamless crypto-to-fiat spending.',
    'pdh.eco.ai': 'AI System',
    'pdh.eco.aiDesc': 'AI-powered infrastructure for partner automation and lead qualification.',
    'pdh.eco.partners': 'Partners',
    'pdh.eco.partnersDesc': 'Global partner community and multi-level ecosystem for collaborative growth.',
    'pdh.explored': 'Explored',
    'pdh.nextSlide': 'Next:',
    'pdh.exploreSystem': 'Explore the system',
    'pdh.exploreMap': 'JetUP Map',
    'pdh.explored.trading': 'Trading',
    'pdh.explored.ai': 'AI',
    'pdh.explored.partner': 'Partners',
    'pdh.explored.ecosystem': 'Ecosystem',
    'pdh.explored.incentives': 'Incentives',
    'pdh.insight.s3': 'Most partners try to scale a product. I scale a system.',
    'pdh.insight.s5': 'Flexibility is not weakness. It\'s the ability to adapt to any situation.',
    'pdh.insight.s6': 'Sustainable growth always beats aggressive promises.',
    'pdh.insight.s8': 'AI doesn\'t replace the partner. AI is a multiplier of their efficiency.',
    'pdh.dennisInsight': 'Dennis insight',
    'pdh.withoutAI': 'Without AI',
    'pdh.withAI': 'With AI',
    'pdh.noai.1': 'Partner answers messages',
    'pdh.noai.2': 'Partner makes calls',
    'pdh.noai.3': 'Partner explains presentation',
    'pdh.noai.4': 'Partner repeats same answers',
    'pdh.withai.1': 'AI answers 24/7',
    'pdh.withai.2': 'AI qualifies leads',
    'pdh.withai.3': 'AI runs the presentation',
    'pdh.withai.4': 'Partner talks only to serious people',
    'pdh.tryDennisAI': 'Try Dennis AI',
    'pdh.aiDemo.q1': 'How much can I earn?',
    'pdh.aiDemo.q2': 'How does copy trading work?',
    'pdh.aiDemo.q3': 'Can I start with $500?',
    'pdh.pipeline.step1': 'Visitor arrives',
    'pdh.pipeline.step2': 'AI starts conversation',
    'pdh.pipeline.step3': 'Lead qualification',
    'pdh.pipeline.step4': 'Meeting booking',
    'pdh.engine.title': 'THE JETUP ENGINE',
    'pdh.engine.products': 'Products',
    'pdh.engine.ai': 'AI Infrastructure',
    'pdh.engine.partners': 'Partner System',
    'pdh.engine.result': 'Scaling Engine',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app-language');
    return (saved === 'ru' || saved === 'de' || saved === 'en') ? saved as Language : 'de';
  });

  useEffect(() => {
    localStorage.setItem('app-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['de'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
